import type { Letter } from "@syncspace/contracts";

/** German letter names after common classroom practice; ß is a letter, not a vowel. */
export const ALPHABET: Letter[] = [
  { letter: "A", nameDe: "Ah", nameIpa: "aː", exampleDe: "Apfel", exampleEn: "apple", noteEn: "Long when stressed before one consonant in many words (Tag). Short in Apfel." },
  { letter: "B", nameDe: "Beh", nameIpa: "beː", exampleDe: "Buch", exampleEn: "book", noteEn: "Sounds like English b at the start of a word. At the end it often becomes p (lieb)." },
  { letter: "C", nameDe: "Tseh", nameIpa: "tseː", exampleDe: "Café", exampleEn: "cafe", noteEn: "Rare alone. With h it writes /ç/ or /x/ (ich, Bach). With k it writes /k/ (Clock is English)." },
  { letter: "D", nameDe: "Deh", nameIpa: "deː", exampleDe: "Dorf", exampleEn: "village", noteEn: "Like English d at the start. Word-final d is usually t (und, Rad)." },
  { letter: "E", nameDe: "Eh", nameIpa: "eː", exampleDe: "Essen", exampleEn: "food / to eat", noteEn: "Long /eː/ in See. Short /ɛ/ in Bett. Unstressed -e is often schwa /ə/." },
  { letter: "F", nameDe: "Eff", nameIpa: "ɛf", exampleDe: "Fenster", exampleEn: "window", noteEn: "Always /f/. The letter v is the one that switches between /f/ and /v/." },
  { letter: "G", nameDe: "Geh", nameIpa: "ɡeː", exampleDe: "Garten", exampleEn: "garden", noteEn: "Start of word: /ɡ/. Final g is often /k/ (Tag). -ig is usually /ɪç/ (richtig)." },
  { letter: "H", nameDe: "Hah", nameIpa: "haː", exampleDe: "Haus", exampleEn: "house", noteEn: "Heard at the start (haben). After a vowel it often only marks length (gehen, sehen)." },
  { letter: "I", nameDe: "Ih", nameIpa: "iː", exampleDe: "Igel", exampleEn: "hedgehog", noteEn: "Long /iː/ in Igel, ihn. Short /ɪ/ in ich, Tisch." },
  { letter: "J", nameDe: "Jott", nameIpa: "jɔt", exampleDe: "Jahr", exampleEn: "year", noteEn: "Like English y in yes, never like English j in jump." },
  { letter: "K", nameDe: "Kah", nameIpa: "kaː", exampleDe: "Kind", exampleEn: "child", noteEn: "Always /k/. ck after a short vowel is the same sound (Ecke)." },
  { letter: "L", nameDe: "Ell", nameIpa: "ɛl", exampleDe: "Lampe", exampleEn: "lamp", noteEn: "A clear /l/, not the dark English l at the end of feel." },
  { letter: "M", nameDe: "Emm", nameIpa: "ɛm", exampleDe: "Mutter", exampleEn: "mother", noteEn: "Same as English m." },
  { letter: "N", nameDe: "Enn", nameIpa: "ɛn", exampleDe: "Name", exampleEn: "name", noteEn: "Same as English n. ng is /ŋ/ (lang), not n+g." },
  { letter: "O", nameDe: "Oh", nameIpa: "oː", exampleDe: "Ofen", exampleEn: "oven", noteEn: "Long /oː/ in Ofen, Boot. Short /ɔ/ in kommen." },
  { letter: "P", nameDe: "Peh", nameIpa: "peː", exampleDe: "Park", exampleEn: "park", noteEn: "Like English p. pf is one affricate (Apfel), not p then a separate f." },
  { letter: "Q", nameDe: "Kuh", nameIpa: "kuː", exampleDe: "Quelle", exampleEn: "source", noteEn: "Almost always qu = /kv/ (Qualität, Quelle)." },
  { letter: "R", nameDe: "Err", nameIpa: "ɛʁ", exampleDe: "Regen", exampleEn: "rain", noteEn: "Often a uvular sound in Germany. After a vowel it frequently vocalizes to /ɐ/ (Uhr, Mutter)." },
  { letter: "S", nameDe: "Ess", nameIpa: "ɛs", exampleDe: "Sonne", exampleEn: "sun", noteEn: "Before a vowel at the start: /z/ (Sonne). After a vowel or at the end: /s/ (Haus, ist). st-/sp- at the start of a word: /ʃt/, /ʃp/." },
  { letter: "T", nameDe: "Teh", nameIpa: "teː", exampleDe: "Tisch", exampleEn: "table", noteEn: "Like English t. tz writes /ts/ after a short vowel (sitzen)." },
  { letter: "U", nameDe: "Uh", nameIpa: "uː", exampleDe: "Uhr", exampleEn: "clock", noteEn: "Long /uː/ in Uhr, Hut. Short /ʊ/ in und, Mutter." },
  { letter: "V", nameDe: "Vau", nameIpa: "faʊ", exampleDe: "Vater", exampleEn: "father", noteEn: "Native words usually /f/ (Vater, vier). Many loanwords keep /v/ (Vase, November)." },
  { letter: "W", nameDe: "Weh", nameIpa: "veː", exampleDe: "Wasser", exampleEn: "water", noteEn: "Always /v/, like English v, never English w." },
  { letter: "X", nameDe: "Iks", nameIpa: "ɪks", exampleDe: "Taxi", exampleEn: "taxi", noteEn: "/ks/. Uncommon in native roots." },
  { letter: "Y", nameDe: "Ypsilon", nameIpa: "ˈʏpsilɔn", exampleDe: "Typ", exampleEn: "type", noteEn: "Usually a rounded /yː/ or /ʏ/, like ü (Typ, System)." },
  { letter: "Z", nameDe: "Zett", nameIpa: "tsɛt", exampleDe: "Zug", exampleEn: "train", noteEn: "Always /ts/, like cats, never English z." },
  { letter: "Ä", nameDe: "Äh", nameIpa: "ɛː", exampleDe: "Mädchen", exampleEn: "girl", noteEn: "Umlaut of a. Often /ɛ/ or /ɛː/. Official spelling: a with two dots, not ae, except when umlauts are unavailable." },
  { letter: "Ö", nameDe: "Öh", nameIpa: "øː", exampleDe: "Öl", exampleEn: "oil", noteEn: "Rounded e. Shape the lips as for /o/ while saying a vowel like German e." },
  { letter: "Ü", nameDe: "Üh", nameIpa: "yː", exampleDe: "Übung", exampleEn: "practice", noteEn: "Rounded i. Say /i/ and round the lips. Short partner is /ʏ/ (fünf)." },
  { letter: "ß", nameDe: "Eszett", nameIpa: "ɛsˈtsɛt", exampleDe: "Straße", exampleEn: "street", noteEn: "Always /s/. It follows a long vowel or diphthong (Fuß, weiß). After a short vowel German writes ss (müssen). Capital ẞ exists in official orthography." },
];
