import type { CoreLexeme, VerbForms } from "@syncspace/contracts";
import { lexId } from "./ids.js";

const draft = "draft" as const;

function noun(
  article: "der" | "die" | "das",
  de: string,
  plural: string | null,
  en: string,
  ipa: string,
  topic: string,
  exampleDe: string,
  exampleEn: string,
  hookEn: string,
  aliases: string[] = [],
): CoreLexeme {
  return {
    id: lexId(de),
    pos: "noun",
    article,
    de,
    plural,
    en,
    aliases,
    ipa,
    topic,
    exampleDe,
    exampleEn,
    hookEn,
    contentStatus: draft,
  };
}

function verb(
  de: string,
  en: string,
  ipa: string,
  topic: string,
  forms: VerbForms,
  exampleDe: string,
  exampleEn: string,
  hookEn: string,
  transitive: boolean,
  aliases: string[] = [],
): CoreLexeme {
  return {
    id: lexId(de),
    pos: "verb",
    article: null,
    de,
    plural: null,
    en,
    aliases,
    ipa,
    topic,
    exampleDe,
    exampleEn,
    hookEn,
    forms,
    transitive,
    contentStatus: draft,
  };
}

function word(
  pos: CoreLexeme["pos"],
  de: string,
  en: string,
  ipa: string,
  topic: string,
  exampleDe: string,
  exampleEn: string,
  hookEn: string,
  aliases: string[] = [],
  disambiguator?: string,
): CoreLexeme {
  return {
    id: lexId(de, disambiguator),
    pos,
    article: null,
    de,
    plural: null,
    en,
    aliases,
    ipa,
    topic,
    exampleDe,
    exampleEn,
    hookEn,
    contentStatus: draft,
  };
}

const NOUNS: CoreLexeme[] = [
  // people
  noun("die", "Frau", "Frauen", "woman", "fʁaʊ", "people", "Die Frau wohnt in Berlin.", "The woman lives in Berlin.", "Mnemonic: Frau is the everyday word for a woman; Frau plus a surname is Ms."),
  noun("der", "Mann", "Männer", "man", "man", "people", "Der Mann heißt Paul.", "The man is called Paul.", "Mnemonic: Mann looks like man, with a doubled n."),
  noun("das", "Kind", "Kinder", "child", "kɪnt", "people", "Das Kind spielt im Garten.", "The child is playing in the garden.", "Mnemonic: Kind is kin plus d; children are Kinder."),
  noun("das", "Baby", "Babys", "baby", "ˈbeːbi", "people", "Das Baby schläft.", "The baby is sleeping.", "Mnemonic: same word as English, German says Bah-bee."),
  noun("der", "Junge", "Jungen", "boy", "ˈjʊŋə", "people", "Der Junge liest ein Buch.", "The boy is reading a book.", "Mnemonic: Junge is a young one; young is jung."),
  noun("das", "Mädchen", "Mädchen", "girl", "ˈmɛːtçən", "people", "Das Mädchen kommt aus Spanien.", "The girl comes from Spain.", "Mnemonic: -chen makes it das; the ch is an ich-Laut."),
  noun("der", "Freund", "Freunde", "friend", "fʁɔʏnt", "people", "Mein Freund wohnt hier.", "My friend lives here.", "Mnemonic: Freund can also mean boyfriend; context decides.", ["boyfriend"]),
  noun("die", "Freundin", "Freundinnen", "friend (female)", "ˈfʁɔʏndɪn", "people", "Meine Freundin lernt Deutsch.", "My friend is learning German.", "Mnemonic: -in marks a female friend; can also mean girlfriend.", ["girlfriend"]),
  noun("die", "Familie", "Familien", "family", "faˈmiːli̯ə", "people", "Meine Familie ist klein.", "My family is small.", "Mnemonic: Familie keeps the familiar family shape."),
  noun("die", "Mutter", "Mütter", "mother", "ˈmʊtɐ", "people", "Meine Mutter kocht heute.", "My mother is cooking today.", "Mnemonic: Mutter looks like mother; ü in the plural Mütter."),
  noun("der", "Vater", "Väter", "father", "ˈfaːtɐ", "people", "Mein Vater arbeitet im Büro.", "My father works in the office.", "Mnemonic: V is /f/ here; Vater is father."),
  noun("die", "Eltern", null, "parents", "ˈɛltɐn", "people", "Meine Eltern wohnen in Köln.", "My parents live in Cologne.", "Mnemonic: already plural; use die Eltern, no extra plural form."),
  noun("die", "Schwester", "Schwestern", "sister", "ˈʃvɛstɐ", "people", "Meine Schwester ist Studentin.", "My sister is a student.", "Mnemonic: Schwester sits next to sister if you hear the schw."),
  noun("der", "Bruder", "Brüder", "brother", "ˈbʁuːdɐ", "people", "Mein Bruder fährt nach Hause.", "My brother is going home.", "Mnemonic: Bruder is brother; plural umlauts to Brüder."),
  noun("der", "Sohn", "Söhne", "son", "zoːn", "people", "Ihr Sohn heißt Max.", "Her son is called Max.", "Mnemonic: Sohn is son with an h that only lengthens the o."),
  noun("die", "Tochter", "Töchter", "daughter", "ˈtɔxtɐ", "people", "Die Tochter geht zur Schule.", "The daughter goes to school.", "Mnemonic: Tochter has the ach-Laut; think daughter at the door."),
  noun("die", "Großmutter", "Großmütter", "grandmother", "ˈɡʁoːsˌmʊtɐ", "people", "Die Großmutter erzählt eine Geschichte.", "Grandmother is telling a story.", "Mnemonic: groß plus Mutter; grandma is the great-size mother.", ["grandma"]),
  noun("der", "Großvater", "Großväter", "grandfather", "ˈɡʁoːsˌfaːtɐ", "people", "Der Großvater liest die Zeitung.", "Grandfather is reading the newspaper.", "Mnemonic: groß plus Vater.", ["grandpa"]),
  noun("der", "Onkel", "Onkel", "uncle", "ˈɔŋkl̩", "people", "Mein Onkel kommt am Sonntag.", "My uncle is coming on Sunday.", "Mnemonic: Onkel is uncle with an o."),
  noun("die", "Tante", "Tanten", "aunt", "ˈtantə", "people", "Die Tante wohnt in Hamburg.", "The aunt lives in Hamburg.", "Mnemonic: Tante is aunt; both are short family words."),
  noun("der", "Nachbar", "Nachbarn", "neighbor", "ˈnaxbaːɐ̯", "people", "Der Nachbar öffnet die Tür.", "The neighbor opens the door.", "Mnemonic: nach plus bar: the person next-after you.", ["neighbour"]),
  noun("die", "Nachbarin", "Nachbarinnen", "neighbor (female)", "ˈnaxbaːʁɪn", "people", "Die Nachbarin hat einen Hund.", "The neighbor has a dog.", "Mnemonic: female pair of Nachbar.", ["neighbour"]),
  noun("der", "Gast", "Gäste", "guest", "ɡast", "people", "Der Gast trinkt Kaffee.", "The guest is drinking coffee.", "Mnemonic: Gast is guest without the ue."),
  noun("die", "Person", "Personen", "person", "pɛʁˈzoːn", "people", "Diese Person heißt Lea.", "This person is called Lea.", "Mnemonic: Person is a clear loan; stress the second syllable."),
  noun("der", "Mensch", "Menschen", "person / human", "mɛnʃ", "people", "Der Mensch braucht Wasser.", "A person needs water.", "Mnemonic: Mensch is the human being, not a polite title."),
  noun("die", "Leute", null, "people", "ˈlɔʏtə", "people", "Viele Leute warten am Bahnhof.", "Many people are waiting at the station.", "Mnemonic: already plural; die Leute means folks."),
  noun("der", "Name", "Namen", "name", "ˈnaːmə", "people", "Mein Name ist Omar.", "My name is Omar.", "Mnemonic: Name is name; long a."),
  noun("der", "Herr", "Herren", "Mr. / gentleman", "hɛʁ", "people", "Guten Tag, Herr Braun!", "Good day, Mr Braun!", "Mnemonic: Herr is the formal male address."),
  noun("der", "Kollege", "Kollegen", "colleague", "kɔˈleːɡə", "people", "Mein Kollege kommt um neun.", "My colleague is coming at nine.", "Mnemonic: Kollege is colleague with a hard g."),
  noun("die", "Kollegin", "Kolleginnen", "colleague (female)", "kɔˈleːɡɪn", "people", "Die Kollegin erklärt den Plan.", "The colleague explains the plan.", "Mnemonic: -in pair of Kollege."),
  noun("der", "Arzt", "Ärzte", "doctor", "aːɐ̯tst", "people", "Der Arzt ist im Krankenhaus.", "The doctor is at the hospital.", "Mnemonic: Arzt ends with /tst/; not English arts.", ["physician"]),
  noun("die", "Ärztin", "Ärztinnen", "doctor (female)", "ˈɛːɐ̯tstɪn", "people", "Die Ärztin fragt nach dem Namen.", "The doctor asks for the name.", "Mnemonic: umlaut plus -in."),
  noun("der", "Lehrer", "Lehrer", "teacher", "ˈleːʁɐ", "people", "Der Lehrer schreibt an die Tafel.", "The teacher writes on the board.", "Mnemonic: lehren is to teach; Lehrer is the teacher."),
  noun("die", "Lehrerin", "Lehrerinnen", "teacher (female)", "ˈleːʁəʁɪn", "people", "Die Lehrerin spricht langsam.", "The teacher speaks slowly.", "Mnemonic: -in pair of Lehrer."),
  noun("der", "Schüler", "Schüler", "pupil", "ˈʃyːlɐ", "people", "Der Schüler öffnet das Heft.", "The pupil opens the exercise book.", "Mnemonic: Schule plus -er; school kid, not only university."),
  noun("die", "Schülerin", "Schülerinnen", "pupil (female)", "ˈʃyːləʁɪn", "people", "Die Schülerin kennt das Wort.", "The pupil knows the word.", "Mnemonic: -in pair of Schüler."),
  noun("der", "Student", "Studenten", "university student", "ʃtuˈdɛnt", "people", "Der Student wohnt in einer Wohnung.", "The student lives in an apartment.", "Mnemonic: Student is the campus learner, not every pupil."),
  noun("die", "Studentin", "Studentinnen", "university student (female)", "ʃtuˈdɛntɪn", "people", "Die Studentin liest das Buch.", "The student is reading the book.", "Mnemonic: -in pair of Student."),

  // home
  noun("das", "Haus", "Häuser", "house", "haʊs", "home", "Das Haus ist alt, aber schön.", "The house is old but nice.", "Mnemonic: Haus is house; au is the sound in house."),
  noun("die", "Wohnung", "Wohnungen", "apartment", "ˈvoːnʊŋ", "home", "Die Wohnung hat zwei Zimmer.", "The apartment has two rooms.", "Mnemonic: wohnen is to live; Wohnung is the lived-in flat.", ["flat"]),
  noun("das", "Zimmer", "Zimmer", "room", "ˈtsɪmɐ", "home", "Das Zimmer ist hell.", "The room is bright.", "Mnemonic: Zimmer starts with /ts/, never English z."),
  noun("die", "Küche", "Küchen", "kitchen", "ˈkʏçə", "home", "Die Küche ist klein.", "The kitchen is small.", "Mnemonic: Küche has ü and an ich-Laut."),
  noun("das", "Bad", "Bäder", "bathroom", "baːt", "home", "Das Bad ist frei.", "The bathroom is free.", "Mnemonic: Bad is bath; long a, final d sounds like t.", ["bath"]),
  noun("das", "Schlafzimmer", "Schlafzimmer", "bedroom", "ˈʃlaːfˌtsɪmɐ", "home", "Das Schlafzimmer hat ein Bett.", "The bedroom has a bed.", "Mnemonic: schlafen plus Zimmer."),
  noun("das", "Wohnzimmer", "Wohnzimmer", "living room", "ˈvoːnˌtsɪmɐ", "home", "Das Wohnzimmer hat ein Sofa.", "The living room has a sofa.", "Mnemonic: wohnen plus Zimmer: the room you live in."),
  noun("der", "Balkon", "Balkone", "balcony", "balˈkɔŋ", "home", "Der Balkon ist sonnig.", "The balcony is sunny.", "Mnemonic: Balkon keeps the French-looking ending."),
  noun("der", "Garten", "Gärten", "garden", "ˈɡaʁtn̩", "home", "Der Garten ist hinter dem Haus.", "The garden is behind the house.", "Mnemonic: Garten is garden with a t."),
  noun("die", "Tür", "Türen", "door", "tyːɐ̯", "home", "Die Tür ist offen.", "The door is open.", "Mnemonic: Tür is door; ü is rounded, not English tour."),
  noun("das", "Fenster", "Fenster", "window", "ˈfɛnstɐ", "home", "Das Fenster geht zur Straße.", "The window faces the street.", "Mnemonic: Fenster is the fenestration word; think fenster-glass."),
  noun("die", "Wand", "Wände", "wall", "vant", "home", "Die Wand ist weiß.", "The wall is white.", "Mnemonic: Wand is the indoor wall, not the city wall."),
  noun("der", "Boden", "Böden", "floor", "ˈboːdn̩", "home", "Der Boden ist sauber.", "The floor is clean.", "Mnemonic: Boden is the ground you stand on.", ["ground"]),
  noun("die", "Decke", "Decken", "ceiling", "ˈdɛkə", "home", "Die Decke ist hoch.", "The ceiling is high.", "Mnemonic: Decke can also mean blanket; here it is the ceiling."),
  noun("das", "Dach", "Dächer", "roof", "dax", "home", "Das Dach ist rot.", "The roof is red.", "Mnemonic: Dach has the ach-Laut; the roof over the house."),
  noun("der", "Keller", "Keller", "basement", "ˈkɛlɐ", "home", "Der Keller ist kalt.", "The basement is cold.", "Mnemonic: Keller is cellar.", ["cellar"]),
  noun("die", "Treppe", "Treppen", "stairs", "ˈtʁɛpə", "home", "Die Treppe führt nach oben.", "The stairs lead up.", "Mnemonic: Treppe is a trip of steps.", ["staircase"]),
  noun("der", "Aufzug", "Aufzüge", "elevator", "ˈaʊftsuk", "home", "Der Aufzug ist defekt.", "The elevator is out of order.", "Mnemonic: auf plus Zug: the thing that pulls you up.", ["lift"]),
  noun("der", "Schlüssel", "Schlüssel", "key", "ˈʃlʏsl̩", "home", "Der Schlüssel liegt auf dem Tisch.", "The key is on the table.", "Mnemonic: Schlüssel is the closer; it locks and unlocks."),
  noun("der", "Tisch", "Tische", "table", "tɪʃ", "home", "Der Tisch steht in der Küche.", "The table is in the kitchen.", "Mnemonic: Tisch is table; short i, final sch."),
  noun("der", "Stuhl", "Stühle", "chair", "ʃtuːl", "home", "Der Stuhl ist frei.", "The chair is free.", "Mnemonic: Stuhl is stool’s taller cousin, a chair."),
  noun("das", "Bett", "Betten", "bed", "bɛt", "home", "Das Bett ist groß.", "The bed is big.", "Mnemonic: Bett is bed with a doubled t."),
  noun("das", "Sofa", "Sofas", "sofa", "ˈzoːfa", "home", "Das Sofa ist bequem.", "The sofa is comfortable.", "Mnemonic: Sofa is sofa; German s is /z/ here.", ["couch"]),
  noun("der", "Schrank", "Schränke", "cupboard", "ʃʁaŋk", "home", "Der Schrank ist voll.", "The cupboard is full.", "Mnemonic: Schrank can be a wardrobe or a cupboard.", ["wardrobe"]),
  noun("das", "Regal", "Regale", "shelf", "ʁeˈɡaːl", "home", "Das Buch steht im Regal.", "The book is on the shelf.", "Mnemonic: Regal is a royal row of shelves."),
  noun("die", "Lampe", "Lampen", "lamp", "ˈlampə", "home", "Die Lampe ist an.", "The lamp is on.", "Mnemonic: Lampe is lamp plus a schwa."),
  noun("der", "Teppich", "Teppiche", "carpet", "ˈtɛpɪç", "home", "Der Teppich liegt im Wohnzimmer.", "The carpet is in the living room.", "Mnemonic: Teppich ends with ich-Laut, not English ch.", ["rug"]),
  noun("das", "Kissen", "Kissen", "pillow", "ˈkɪsn̩", "home", "Das Kissen ist weich.", "The pillow is soft.", "Mnemonic: Kissen is a kiss of a cushion.", ["cushion"]),
  noun("der", "Spiegel", "Spiegel", "mirror", "ˈʃpiːɡl̩", "home", "Der Spiegel ist im Bad.", "The mirror is in the bathroom.", "Mnemonic: Spiegel starts like spiel; you play at looking."),
  noun("der", "Teller", "Teller", "plate", "ˈtɛlɐ", "home", "Der Teller ist leer.", "The plate is empty.", "Mnemonic: Teller tells you dinner is served."),
  noun("die", "Tasse", "Tassen", "cup", "ˈtasə", "home", "Die Tasse ist heiß.", "The cup is hot.", "Mnemonic: Tasse is a cup, not a glass."),
  noun("das", "Glas", "Gläser", "glass", "ɡlaːs", "home", "Das Glas steht auf dem Tisch.", "The glass is on the table.", "Mnemonic: Glas is glass; plural umlauts to Gläser."),
  noun("das", "Messer", "Messer", "knife", "ˈmɛsɐ", "home", "Das Messer ist scharf.", "The knife is sharp.", "Mnemonic: Messer is not mess; it is the knife."),
  noun("die", "Gabel", "Gabeln", "fork", "ˈɡaːbl̩", "home", "Die Gabel liegt links.", "The fork is on the left.", "Mnemonic: Gabel is the forked tool."),
  noun("der", "Löffel", "Löffel", "spoon", "ˈlœfl̩", "home", "Der Löffel ist in der Suppe.", "The spoon is in the soup.", "Mnemonic: Löffel has ö; scoop with a little shovel."),
  noun("der", "Topf", "Töpfe", "pot", "tɔpf", "home", "Der Topf steht auf dem Herd.", "The pot is on the stove.", "Mnemonic: Topf is pot; pf is one affricate."),
  noun("der", "Kühlschrank", "Kühlschränke", "fridge", "ˈkyːlˌʃʁaŋk", "home", "Die Milch ist im Kühlschrank.", "The milk is in the fridge.", "Mnemonic: kühl plus Schrank: the cool cupboard.", ["refrigerator"]),
  noun("der", "Herd", "Herde", "stove", "heːɐ̯t", "home", "Der Herd ist heiß.", "The stove is hot.", "Mnemonic: Herd is the cooker, not a herd of animals.", ["cooker"]),

  // city
  noun("die", "Stadt", "Städte", "city", "ʃtat", "city", "Die Stadt ist groß.", "The city is big.", "Mnemonic: Stadt is the city; Staat with aa is the state."),
  noun("das", "Dorf", "Dörfer", "village", "dɔʁf", "city", "Das Dorf hat eine Kirche.", "The village has a church.", "Mnemonic: Dorf is a compact village word."),
  noun("das", "Land", "Länder", "country", "lant", "city", "Deutschland ist ein Land.", "Germany is a country.", "Mnemonic: Land is country or countryside; plural Länder.", ["countryside"]),
  noun("die", "Straße", "Straßen", "street", "ˈʃtʁaːsə", "city", "Die Straße ist ruhig.", "The street is quiet.", "Mnemonic: ß here; Straße is street.", ["road"]),
  noun("der", "Platz", "Plätze", "square", "plats", "city", "Der Platz ist voll.", "The square is full.", "Mnemonic: Platz is a town square or a seat; here it is the square."),
  noun("der", "Markt", "Märkte", "market", "maʁkt", "city", "Der Markt ist am Samstag.", "The market is on Saturday.", "Mnemonic: Markt is market."),
  noun("der", "Park", "Parks", "park", "paʁk", "city", "Der Park ist schön.", "The park is nice.", "Mnemonic: Park is park."),
  noun("die", "Brücke", "Brücken", "bridge", "ˈbʁʏkə", "city", "Die Brücke ist alt.", "The bridge is old.", "Mnemonic: Brücke has ü; a bridge over the brook."),
  noun("die", "Kirche", "Kirchen", "church", "ˈkɪʁçə", "city", "Die Kirche steht im Zentrum.", "The church is in the centre.", "Mnemonic: Kirche ends with ich-Laut."),
  noun("das", "Museum", "Museen", "museum", "muˈzeːʊm", "city", "Das Museum öffnet um zehn.", "The museum opens at ten.", "Mnemonic: Museum; stress the second syllable."),
  noun("das", "Kino", "Kinos", "cinema", "ˈkiːno", "city", "Das Kino ist neben dem Café.", "The cinema is next to the cafe.", "Mnemonic: Kino is cinema without the ma.", ["movies"]),
  noun("das", "Theater", "Theater", "theater", "teˈaːtɐ", "city", "Das Theater beginnt um acht.", "The theater starts at eight.", "Mnemonic: Theater keeps the three syllables.", ["theatre"]),
  noun("das", "Restaurant", "Restaurants", "restaurant", "ʁɛstoˈʁɑ̃", "city", "Das Restaurant ist teuer.", "The restaurant is expensive.", "Mnemonic: loanword; last syllable is nasal in many speakers."),
  noun("das", "Café", "Cafés", "cafe", "kaˈfeː", "city", "Das Café hat guten Kuchen.", "The cafe has good cake.", "Mnemonic: Café is cafe; stress the second syllable."),
  noun("das", "Hotel", "Hotels", "hotel", "hoˈtɛl", "city", "Das Hotel liegt am Bahnhof.", "The hotel is by the station.", "Mnemonic: Hotel; stress the second syllable."),
  noun("die", "Bank", "Banken", "bank", "baŋk", "city", "Die Bank öffnet um neun.", "The bank opens at nine.", "Mnemonic: Bank is the money bank here, not a bench."),
  noun("die", "Post", null, "post office", "pɔst", "city", "Die Post ist neben der Bank.", "The post office is next to the bank.", "Mnemonic: die Post is the postal service."),
  noun("die", "Apotheke", "Apotheken", "pharmacy", "apoˈteːkə", "city", "Die Apotheke ist um die Ecke.", "The pharmacy is around the corner.", "Mnemonic: Apotheke is the chemist, not a grocery.", ["chemist"]),
  noun("der", "Supermarkt", "Supermärkte", "supermarket", "ˈzuːpɐmaʁkt", "city", "Der Supermarkt hat Brot.", "The supermarket has bread.", "Mnemonic: Super plus Markt."),
  noun("die", "Bäckerei", "Bäckereien", "bakery", "bɛkəˈʁaɪ", "city", "Die Bäckerei öffnet früh.", "The bakery opens early.", "Mnemonic: Bäcker is baker; -ei is the shop."),
  noun("das", "Geschäft", "Geschäfte", "shop", "ɡəˈʃɛft", "city", "Das Geschäft schließt um sechs.", "The shop closes at six.", "Mnemonic: Geschäft is a shop or a deal.", ["store"]),
  noun("die", "Bibliothek", "Bibliotheken", "library", "biblioˈteːk", "city", "Die Bibliothek ist still.", "The library is quiet.", "Mnemonic: long word; stress -thek."),
  noun("das", "Krankenhaus", "Krankenhäuser", "hospital", "ˈkʁaŋkn̩ˌhaʊs", "city", "Das Krankenhaus ist neu.", "The hospital is new.", "Mnemonic: krank plus Haus: the sick-house."),
  noun("die", "Polizei", null, "police", "poliˈtsaɪ", "city", "Die Polizei hilft.", "The police help.", "Mnemonic: z is /ts/; Polizei ends like two."),
  noun("die", "Ampel", "Ampeln", "traffic light", "ˈampl̩", "city", "Die Ampel ist rot.", "The traffic light is red.", "Mnemonic: Ampel is the light that says stop or go."),
  noun("die", "Kreuzung", "Kreuzungen", "intersection", "ˈkʁɔʏtsʊŋ", "city", "Die Kreuzung ist gefährlich.", "The intersection is dangerous.", "Mnemonic: Kreuz is a cross; Kreuzung is a crossing."),
  noun("die", "Haltestelle", "Haltestellen", "stop", "ˈhaltəˌʃtɛlə", "city", "Die Haltestelle ist hier.", "The stop is here.", "Mnemonic: halten plus Stelle: the holding place.", ["bus stop"]),
  noun("der", "Bahnhof", "Bahnhöfe", "train station", "ˈbaːnhoːf", "city", "Der Bahnhof ist groß.", "The station is big.", "Mnemonic: Bahn plus Hof: the rail courtyard.", ["station"]),
  noun("der", "Flughafen", "Flughäfen", "airport", "ˈfluːkˌhaːfn̩", "city", "Der Flughafen liegt außerhalb.", "The airport is outside town.", "Mnemonic: Flug plus Hafen: flight-harbour."),
  noun("der", "Fluss", "Flüsse", "river", "flʊs", "city", "Der Fluss ist breit.", "The river is wide.", "Mnemonic: Fluss is the flowing water."),
  noun("der", "See", "Seen", "lake", "zeː", "city", "Der See ist kalt.", "The lake is cold.", "Mnemonic: der See is a lake; das Meer is the sea."),
  noun("das", "Meer", "Meere", "sea", "meːɐ̯", "city", "Das Meer ist blau.", "The sea is blue.", "Mnemonic: Meer is the sea, not a lake."),
  noun("der", "Berg", "Berge", "mountain", "bɛʁk", "city", "Der Berg ist hoch.", "The mountain is high.", "Mnemonic: Berg is a mountain; final g often sounds like k."),
  noun("der", "Wald", "Wälder", "forest", "valt", "city", "Der Wald ist dunkel.", "The forest is dark.", "Mnemonic: Wald is woods; final d sounds like t.", ["woods"]),

  // food
  noun("der", "Apfel", "Äpfel", "apple", "ˈapfl̩", "food", "Der Apfel ist rot.", "The apple is red.", "Mnemonic: Apfel is apple; pf is one sound."),
  noun("das", "Brot", "Brote", "bread", "bʁoːt", "food", "Das Brot ist frisch.", "The bread is fresh.", "Mnemonic: Brot is bread; long o."),
  noun("das", "Wasser", null, "water", "ˈvasɐ", "food", "Ich trinke Wasser.", "I drink water.", "Mnemonic: Wasser is water; w is /v/."),
  noun("das", "Frühstück", "Frühstücke", "breakfast", "ˈfʁyːˌʃtʏk", "food", "Das Frühstück ist um acht.", "Breakfast is at eight.", "Mnemonic: früh plus Stück: an early piece."),
  noun("das", "Mittagessen", "Mittagessen", "lunch", "ˈmɪtaːkˌɛsn̩", "food", "Das Mittagessen ist fertig.", "Lunch is ready.", "Mnemonic: Mittag plus Essen."),
  noun("das", "Abendessen", "Abendessen", "dinner", "ˈaːbn̩tˌɛsn̩", "food", "Das Abendessen ist um sieben.", "Dinner is at seven.", "Mnemonic: Abend plus Essen.", ["supper"]),
  noun("der", "Kaffee", "Kaffees", "coffee", "ˈkafe", "food", "Der Kaffee ist heiß.", "The coffee is hot.", "Mnemonic: Kaffee has two f and two e."),
  noun("der", "Tee", "Tees", "tea", "teː", "food", "Der Tee ist gut.", "The tea is good.", "Mnemonic: Tee is tea; long e, doubled e."),
  noun("die", "Milch", null, "milk", "mɪlç", "food", "Die Milch ist kalt.", "The milk is cold.", "Mnemonic: Milch ends with ich-Laut."),
  noun("der", "Saft", "Säfte", "juice", "zaft", "food", "Der Saft ist süß.", "The juice is sweet.", "Mnemonic: Saft is juice, not soft."),
  noun("das", "Bier", "Biere", "beer", "biːɐ̯", "food", "Das Bier ist kalt.", "The beer is cold.", "Mnemonic: Bier is beer."),
  noun("der", "Wein", "Weine", "wine", "vaɪn", "food", "Der Wein kommt aus Spanien.", "The wine comes from Spain.", "Mnemonic: Wein is wine; ei as in mine."),
  noun("die", "Suppe", "Suppen", "soup", "ˈzʊpə", "food", "Die Suppe ist warm.", "The soup is warm.", "Mnemonic: Suppe is soup plus schwa."),
  noun("der", "Salat", "Salate", "salad", "zaˈlaːt", "food", "Der Salat ist frisch.", "The salad is fresh.", "Mnemonic: Salat is salad; stress the second syllable."),
  noun("das", "Fleisch", null, "meat", "flaɪʃ", "food", "Das Fleisch ist teuer.", "The meat is expensive.", "Mnemonic: Fleisch is flesh that you eat."),
  noun("der", "Fisch", "Fische", "fish", "fɪʃ", "food", "Der Fisch schmeckt gut.", "The fish tastes good.", "Mnemonic: Fisch is fish."),
  noun("das", "Huhn", "Hühner", "chicken", "huːn", "food", "Das Huhn ist im Ofen.", "The chicken is in the oven.", "Mnemonic: Huhn is the bird on the plate.", ["hen"]),
  noun("der", "Käse", "Käse", "cheese", "ˈkɛːzə", "food", "Der Käse ist stark.", "The cheese is strong.", "Mnemonic: Käse is cheese; ä is open."),
  noun("die", "Butter", null, "butter", "ˈbʊtɐ", "food", "Die Butter ist im Kühlschrank.", "The butter is in the fridge.", "Mnemonic: Butter is butter."),
  noun("das", "Ei", "Eier", "egg", "aɪ", "food", "Das Ei ist gekocht.", "The egg is boiled.", "Mnemonic: Ei is egg; tiny word, same diphthong as ein."),
  noun("der", "Reis", null, "rice", "ʁaɪs", "food", "Der Reis ist fertig.", "The rice is ready.", "Mnemonic: Reis is rice, not a journey (Reise)."),
  noun("die", "Nudel", "Nudeln", "noodle", "ˈnuːdl̩", "food", "Die Nudel ist lang.", "The noodle is long.", "Mnemonic: Nudel is noodle; plural Nudeln often means pasta.", ["pasta"]),
  noun("die", "Kartoffel", "Kartoffeln", "potato", "kaʁˈtɔfl̩", "food", "Die Kartoffel ist heiß.", "The potato is hot.", "Mnemonic: Kartoffel is a long everyday word for potato."),
  noun("das", "Gemüse", "Gemüse", "vegetables", "ɡəˈmyːzə", "food", "Das Gemüse ist frisch.", "The vegetables are fresh.", "Mnemonic: Gemüse is the vegetable group, usually das."),
  noun("das", "Obst", null, "fruit", "oːpst", "food", "Das Obst ist süß.", "The fruit is sweet.", "Mnemonic: Obst is fruit as a group, not one apple."),
  noun("die", "Banane", "Bananen", "banana", "baˈnaːnə", "food", "Die Banane ist gelb.", "The banana is yellow.", "Mnemonic: Banane is banana minus one a."),
  noun("die", "Orange", "Orangen", "orange", "oˈʁaŋʒə", "food", "Die Orange ist saftig.", "The orange is juicy.", "Mnemonic: Orange is the fruit; der Orangensaft is the juice."),
  noun("die", "Tomate", "Tomaten", "tomato", "toˈmaːtə", "food", "Die Tomate ist rot.", "The tomato is red.", "Mnemonic: Tomate is tomato without the to at the end."),
  noun("das", "Salz", null, "salt", "zalts", "food", "Das Salz steht auf dem Tisch.", "The salt is on the table.", "Mnemonic: Salz ends with /ts/."),
  noun("der", "Pfeffer", null, "pepper", "ˈpfɛfɐ", "food", "Der Pfeffer ist scharf.", "The pepper is hot.", "Mnemonic: Pfeffer starts with pf."),
  noun("der", "Zucker", null, "sugar", "ˈtsʊkɐ", "food", "Der Zucker ist im Tee.", "The sugar is in the tea.", "Mnemonic: Zucker starts with /ts/, never English z."),
  noun("der", "Kuchen", "Kuchen", "cake", "ˈkuːxn̩", "food", "Der Kuchen schmeckt gut.", "The cake tastes good.", "Mnemonic: Kuchen is cake; ch is ach-Laut after u."),
  noun("das", "Eis", null, "ice cream", "aɪs", "food", "Das Eis ist kalt.", "The ice cream is cold.", "Mnemonic: Eis is ice and ice cream in everyday talk.", ["ice"]),
  noun("die", "Schokolade", "Schokoladen", "chocolate", "ʃokoˈlaːdə", "food", "Die Schokolade ist süß.", "The chocolate is sweet.", "Mnemonic: long word; stress -la-."),
  noun("die", "Pizza", "Pizzen", "pizza", "ˈpɪtsa", "food", "Die Pizza ist warm.", "The pizza is warm.", "Mnemonic: Pizza; German plural is often Pizzen."),
  noun("die", "Wurst", "Würste", "sausage", "vʊʁst", "food", "Die Wurst ist auf dem Brot.", "The sausage is on the bread.", "Mnemonic: Wurst is sausage; w is /v/."),

  // time
  noun("die", "Zeit", "Zeiten", "time", "tsaɪt", "time", "Ich habe keine Zeit.", "I have no time.", "Mnemonic: Zeit starts with /ts/; time you can count or spend."),
  noun("der", "Tag", "Tage", "day", "taːk", "time", "Der Tag ist lang.", "The day is long.", "Mnemonic: Tag is day; final g often /k/."),
  noun("die", "Woche", "Wochen", "week", "ˈvɔxə", "time", "Die Woche hat sieben Tage.", "The week has seven days.", "Mnemonic: Woche is week; ch is ach-Laut."),
  noun("der", "Monat", "Monate", "month", "ˈmoːnat", "time", "Der Monat ist kalt.", "The month is cold.", "Mnemonic: Monat is month."),
  noun("das", "Jahr", "Jahre", "year", "jaːɐ̯", "time", "Das Jahr hat zwölf Monate.", "The year has twelve months.", "Mnemonic: Jahr starts with /j/, like English y."),
  noun("die", "Stunde", "Stunden", "hour", "ˈʃtʊndə", "time", "Die Stunde ist vorbei.", "The hour is over.", "Mnemonic: Stunde is hour, not a student."),
  noun("die", "Minute", "Minuten", "minute", "miˈnuːtə", "time", "Eine Minute, bitte.", "One minute, please.", "Mnemonic: Minute; stress the second syllable."),
  noun("der", "Morgen", "Morgen", "morning", "ˈmɔʁɡn̩", "time", "Der Morgen ist kalt.", "The morning is cold.", "Mnemonic: capital Morgen is morning; lowercase morgen is tomorrow."),
  noun("der", "Abend", "Abende", "evening", "ˈaːbn̩t", "time", "Der Abend ist ruhig.", "The evening is quiet.", "Mnemonic: Abend is evening; long a."),
  noun("die", "Nacht", "Nächte", "night", "naxt", "time", "Die Nacht ist dunkel.", "The night is dark.", "Mnemonic: Nacht is night; ach-Laut."),
  noun("der", "Mittag", "Mittage", "midday", "ˈmɪtaːk", "time", "Am Mittag essen wir.", "At midday we eat.", "Mnemonic: Mitte plus Tag: the middle of the day.", ["noon"]),
  noun("die", "Uhr", "Uhren", "clock", "uːɐ̯", "time", "Die Uhr ist kaputt.", "The clock is broken.", "Mnemonic: Uhr is clock and the word in es ist acht Uhr.", ["watch"]),
  noun("der", "Termin", "Termine", "appointment", "tɛɐ̯ˈmiːn", "time", "Ich habe um zehn einen Termin.", "I have an appointment at ten.", "Mnemonic: Termin is a fixed time slot."),
  noun("die", "Pause", "Pausen", "break", "ˈpaʊzə", "time", "Die Pause ist kurz.", "The break is short.", "Mnemonic: Pause is a pause you take."),
  noun("die", "Ferien", null, "holidays", "ˈfeːʁiən", "time", "Die Ferien beginnen im Juli.", "The holidays start in July.", "Mnemonic: already plural; school holidays more than a trip.", ["vacation"]),
  noun("der", "Urlaub", "Urlaube", "vacation", "ˈuːɐ̯laʊp", "time", "Der Urlaub ist im Sommer.", "The vacation is in summer.", "Mnemonic: Urlaub is time off work, often a trip.", ["holiday"]),
  noun("das", "Wochenende", "Wochenenden", "weekend", "ˈvɔxn̩ˌɛndə", "time", "Das Wochenende ist frei.", "The weekend is free.", "Mnemonic: Woche plus Ende."),
  noun("der", "Geburtstag", "Geburtstage", "birthday", "ɡəˈbuːɐ̯tsˌtaːk", "time", "Heute ist mein Geburtstag.", "Today is my birthday.", "Mnemonic: Geburt plus Tag: birth-day."),
  noun("der", "Montag", "Montage", "Monday", "ˈmoːntaːk", "time", "Am Montag arbeite ich.", "On Monday I work.", "Mnemonic: Montag starts the work week."),
  noun("der", "Dienstag", "Dienstage", "Tuesday", "ˈdiːnstaːk", "time", "Am Dienstag lerne ich.", "On Tuesday I study.", "Mnemonic: Dienstag is the service day in the old week names."),
  noun("der", "Mittwoch", "Mittwoche", "Wednesday", "ˈmɪtvɔx", "time", "Am Mittwoch ist Markt.", "On Wednesday there is a market.", "Mnemonic: Mitte plus Woche: mid-week."),
  noun("der", "Donnerstag", "Donnerstage", "Thursday", "ˈdɔnɐstaːk", "time", "Am Donnerstag kaufe ich ein.", "On Thursday I go shopping.", "Mnemonic: Donnerstag; keep the n."),
  noun("der", "Freitag", "Freitage", "Friday", "ˈfʁaɪtaːk", "time", "Am Freitag sind wir frei.", "On Friday we are free.", "Mnemonic: frei plus Tag: a free-feeling day."),
  noun("der", "Samstag", "Samstage", "Saturday", "ˈzamstaːk", "time", "Am Samstag schlafe ich lange.", "On Saturday I sleep late.", "Mnemonic: Samstag is Saturday in much of Germany.", ["Saturday"]),
  noun("der", "Sonntag", "Sonntage", "Sunday", "ˈzɔntaːk", "time", "Am Sonntag ist Ruhe.", "On Sunday there is rest.", "Mnemonic: Sonne plus Tag: sun-day."),
  noun("der", "Januar", "Januare", "January", "ˈjanuaːɐ̯", "time", "Im Januar ist es kalt.", "In January it is cold.", "Mnemonic: Januar is January; J is /j/."),
  noun("der", "Sommer", "Sommer", "summer", "ˈzɔmɐ", "time", "Der Sommer ist warm.", "The summer is warm.", "Mnemonic: Sommer is summer."),
  noun("der", "Winter", "Winter", "winter", "ˈvɪntɐ", "time", "Der Winter ist kalt.", "The winter is cold.", "Mnemonic: Winter is winter; w is /v/."),

  // travel
  noun("der", "Zug", "Züge", "train", "tsuːk", "travel", "Der Zug fährt um acht.", "The train leaves at eight.", "Mnemonic: Zug starts with /ts/; a train that pulls."),
  noun("der", "Bus", "Busse", "bus", "bʊs", "travel", "Der Bus kommt gleich.", "The bus is coming soon.", "Mnemonic: Bus is bus."),
  noun("das", "Auto", "Autos", "car", "ˈaʊto", "travel", "Das Auto ist neu.", "The car is new.", "Mnemonic: Auto is the everyday car word.", ["car"]),
  noun("das", "Taxi", "Taxis", "taxi", "ˈtaksi", "travel", "Das Taxi wartet vor dem Hotel.", "The taxi is waiting in front of the hotel.", "Mnemonic: Taxi is taxi."),
  noun("das", "Fahrrad", "Fahrräder", "bicycle", "ˈfaːɐ̯ʁaːt", "travel", "Das Fahrrad steht im Keller.", "The bicycle is in the basement.", "Mnemonic: fahren plus Rad: a travel-wheel.", ["bike"]),
  noun("das", "Flugzeug", "Flugzeuge", "airplane", "ˈfluːktsɔʏk", "travel", "Das Flugzeug fliegt nach Rom.", "The airplane flies to Rome.", "Mnemonic: Flug plus Zeug: flying stuff.", ["plane"]),
  noun("das", "Schiff", "Schiffe", "ship", "ʃɪf", "travel", "Das Schiff ist groß.", "The ship is big.", "Mnemonic: Schiff is ship; doubled f."),
  noun("das", "Ticket", "Tickets", "ticket", "ˈtɪkət", "travel", "Das Ticket ist teuer.", "The ticket is expensive.", "Mnemonic: Ticket is a loan; Fahrkarte is the older pair."),
  noun("die", "Fahrkarte", "Fahrkarten", "ticket", "ˈfaːɐ̯kaʁtə", "travel", "Eine Fahrkarte nach Berlin, bitte.", "A ticket to Berlin, please.", "Mnemonic: fahren plus Karte: a travel card."),
  noun("der", "Reisepass", "Reisepässe", "passport", "ˈʁaɪzəˌpas", "travel", "Der Reisepass ist in der Tasche.", "The passport is in the bag.", "Mnemonic: Reise plus Pass."),
  noun("der", "Koffer", "Koffer", "suitcase", "ˈkɔfɐ", "travel", "Der Koffer ist schwer.", "The suitcase is heavy.", "Mnemonic: Koffer is the hard case you carry."),
  noun("die", "Tasche", "Taschen", "bag", "ˈtaʃə", "travel", "Die Tasche ist voll.", "The bag is full.", "Mnemonic: Tasche is a bag or a pocket.", ["handbag"]),
  noun("der", "Rucksack", "Rucksäcke", "backpack", "ˈʁʊkzak", "travel", "Der Rucksack liegt unter dem Sitz.", "The backpack is under the seat.", "Mnemonic: Rücken plus Sack: a sack for the back.", ["rucksack"]),
  noun("das", "Gepäck", null, "luggage", "ɡəˈpɛk", "travel", "Das Gepäck ist am Band.", "The luggage is on the belt.", "Mnemonic: Gepäck is luggage as a mass.", ["baggage"]),
  noun("die", "Reise", "Reisen", "trip", "ˈʁaɪzə", "travel", "Die Reise ist lang.", "The trip is long.", "Mnemonic: Reise is a journey; Reis without e is rice.", ["journey"]),
  noun("das", "Gleis", "Gleise", "track", "ɡlaɪs", "travel", "Der Zug fährt von Gleis drei.", "The train leaves from track three.", "Mnemonic: Gleis is the rail track number."),
  noun("der", "Bahnsteig", "Bahnsteige", "platform", "ˈbaːnʃtaɪk", "travel", "Der Bahnsteig ist voll.", "The platform is full.", "Mnemonic: Bahn plus Steig: the rail walkway."),
  noun("die", "Abfahrt", "Abfahrten", "departure", "ˈapfaːɐ̯t", "travel", "Die Abfahrt ist um neun.", "Departure is at nine.", "Mnemonic: ab plus Fahrt: the driving-off."),
  noun("die", "Ankunft", "Ankünfte", "arrival", "ˈankʊnft", "travel", "Die Ankunft ist pünktlich.", "The arrival is on time.", "Mnemonic: an plus Kunft: the coming-to."),
  noun("die", "Verspätung", "Verspätungen", "delay", "fɛɐ̯ˈʃpɛːtʊŋ", "travel", "Die Verspätung beträgt zehn Minuten.", "The delay is ten minutes.", "Mnemonic: spät plus ung: a late-ness."),
  noun("die", "U-Bahn", "U-Bahnen", "subway", "ˈuːbaːn", "travel", "Die U-Bahn fährt unter der Stadt.", "The subway runs under the city.", "Mnemonic: Untergrundbahn, shortened to U-Bahn.", ["underground", "metro"]),
  noun("die", "Straßenbahn", "Straßenbahnen", "tram", "ˈʃtʁaːsn̩baːn", "travel", "Die Straßenbahn hält hier.", "The tram stops here.", "Mnemonic: Straße plus Bahn: street rail.", ["streetcar"]),

  // weather
  noun("das", "Wetter", null, "weather", "ˈvɛtɐ", "weather", "Das Wetter ist schön.", "The weather is nice.", "Mnemonic: Wetter is weather; w is /v/."),
  noun("die", "Sonne", "Sonnen", "sun", "ˈzɔnə", "weather", "Die Sonne scheint.", "The sun is shining.", "Mnemonic: Sonne is sun; doubled n."),
  noun("der", "Regen", null, "rain", "ˈʁeːɡn̩", "weather", "Der Regen beginnt.", "The rain is starting.", "Mnemonic: Regen is rain."),
  noun("der", "Schnee", null, "snow", "ʃneː", "weather", "Der Schnee ist weiß.", "The snow is white.", "Mnemonic: Schnee is snow; long e."),
  noun("der", "Wind", "Winde", "wind", "vɪnt", "weather", "Der Wind ist stark.", "The wind is strong.", "Mnemonic: Wind is wind; final d as t."),
  noun("die", "Wolke", "Wolken", "cloud", "ˈvɔlkə", "weather", "Die Wolke ist grau.", "The cloud is grey.", "Mnemonic: Wolke is a woolly cloud."),
  noun("der", "Sturm", "Stürme", "storm", "ʃtʊʁm", "weather", "Der Sturm kommt in der Nacht.", "The storm is coming at night.", "Mnemonic: Sturm is storm."),
  noun("der", "Nebel", "Nebel", "fog", "ˈneːbl̩", "weather", "Der Nebel ist dicht.", "The fog is thick.", "Mnemonic: Nebel is fog over the fields."),
  noun("der", "Himmel", "Himmel", "sky", "ˈhɪml̩", "weather", "Der Himmel ist blau.", "The sky is blue.", "Mnemonic: Himmel is sky or heaven in older texts."),
  noun("die", "Temperatur", "Temperaturen", "temperature", "tɛmpəʁaˈtuːɐ̯", "weather", "Die Temperatur ist niedrig.", "The temperature is low.", "Mnemonic: long loan; stress the last syllable."),

  // body
  noun("der", "Körper", "Körper", "body", "ˈkœʁpɐ", "body", "Der Körper braucht Schlaf.", "The body needs sleep.", "Mnemonic: Körper has ö; the whole body."),
  noun("der", "Kopf", "Köpfe", "head", "kɔpf", "body", "Mein Kopf tut weh.", "My head hurts.", "Mnemonic: Kopf is head; pf is one sound."),
  noun("das", "Haar", "Haare", "hair", "haːɐ̯", "body", "Das Haar ist lang.", "The hair is long.", "Mnemonic: Haar is hair; long a."),
  noun("das", "Gesicht", "Gesichter", "face", "ɡəˈzɪçt", "body", "Das Gesicht ist müde.", "The face looks tired.", "Mnemonic: Gesicht is the seen-part of you."),
  noun("das", "Auge", "Augen", "eye", "ˈaʊɡə", "body", "Das Auge ist blau.", "The eye is blue.", "Mnemonic: Auge is eye; au as in house."),
  noun("das", "Ohr", "Ohren", "ear", "oːɐ̯", "body", "Das Ohr ist rot.", "The ear is red.", "Mnemonic: Ohr is ear; long o."),
  noun("die", "Nase", "Nasen", "nose", "ˈnaːzə", "body", "Die Nase ist kalt.", "The nose is cold.", "Mnemonic: Nase is nose."),
  noun("der", "Mund", "Münder", "mouth", "mʊnt", "body", "Der Mund ist trocken.", "The mouth is dry.", "Mnemonic: Mund is mouth; final d as t."),
  noun("der", "Zahn", "Zähne", "tooth", "tsaːn", "body", "Der Zahn tut weh.", "The tooth hurts.", "Mnemonic: Zahn starts with /ts/; a tooth."),
  noun("der", "Hals", "Hälse", "neck", "hals", "body", "Mein Hals ist rot.", "My neck is red.", "Mnemonic: Hals is neck or throat."),
  noun("der", "Arm", "Arme", "arm", "aʁm", "body", "Der Arm ist lang.", "The arm is long.", "Mnemonic: Arm is arm."),
  noun("die", "Hand", "Hände", "hand", "hant", "body", "Die Hand ist warm.", "The hand is warm.", "Mnemonic: Hand is hand; plural umlauts."),
  noun("der", "Finger", "Finger", "finger", "ˈfɪŋɐ", "body", "Der Finger ist nass.", "The finger is wet.", "Mnemonic: Finger is finger."),
  noun("das", "Bein", "Beine", "leg", "baɪn", "body", "Das Bein ist müde.", "The leg is tired.", "Mnemonic: Bein is a leg, not a bone (Knochen)."),
  noun("der", "Fuß", "Füße", "foot", "fuːs", "body", "Der Fuß ist klein.", "The foot is small.", "Mnemonic: Fuß is foot; ß, long u."),
  noun("das", "Knie", "Knie", "knee", "kniː", "body", "Das Knie tut weh.", "The knee hurts.", "Mnemonic: Knie is knee; kn stays k plus n."),
  noun("der", "Rücken", "Rücken", "back", "ˈʁʏkn̩", "body", "Mein Rücken ist steif.", "My back is stiff.", "Mnemonic: Rücken is the back you carry a Rucksack on."),
  noun("der", "Bauch", "Bäuche", "belly", "baʊx", "body", "Der Bauch ist voll.", "The belly is full.", "Mnemonic: Bauch is belly; ach-Laut after au.", ["stomach"]),

  // clothes
  noun("die", "Kleidung", null, "clothing", "ˈklaɪdʊŋ", "clothes", "Die Kleidung ist sauber.", "The clothing is clean.", "Mnemonic: Kleid plus ung: clothing as a set."),
  noun("das", "Hemd", "Hemden", "shirt", "hɛmt", "clothes", "Das Hemd ist weiß.", "The shirt is white.", "Mnemonic: Hemd is a shirt, often a button shirt."),
  noun("die", "Hose", "Hosen", "trousers", "ˈhoːzə", "clothes", "Die Hose ist schwarz.", "The trousers are black.", "Mnemonic: Hose is a pair of trousers; one item, die Hose.", ["pants"]),
  noun("der", "Rock", "Röcke", "skirt", "ʁɔk", "clothes", "Der Rock ist kurz.", "The skirt is short.", "Mnemonic: Rock is a skirt here, not rock music."),
  noun("das", "Kleid", "Kleider", "dress", "klaɪt", "clothes", "Das Kleid ist schön.", "The dress is beautiful.", "Mnemonic: Kleid is a dress; final d as t."),
  noun("die", "Jacke", "Jacken", "jacket", "ˈjakə", "clothes", "Die Jacke ist warm.", "The jacket is warm.", "Mnemonic: Jacke is jacket minus t."),
  noun("der", "Mantel", "Mäntel", "coat", "ˈmantl̩", "clothes", "Der Mantel ist lang.", "The coat is long.", "Mnemonic: Mantel is a coat you mantle yourself in."),
  noun("der", "Pullover", "Pullover", "sweater", "pʊˈloːvɐ", "clothes", "Der Pullover ist weich.", "The sweater is soft.", "Mnemonic: you pull it over; German keeps the English shape.", ["jumper"]),
  noun("das", "T-Shirt", "T-Shirts", "T-shirt", "ˈtiːʃœʁt", "clothes", "Das T-Shirt ist blau.", "The T-shirt is blue.", "Mnemonic: spoken Tee-Shirt."),
  noun("der", "Schuh", "Schuhe", "shoe", "ʃuː", "clothes", "Der Schuh ist neu.", "The shoe is new.", "Mnemonic: Schuh is shoe; h marks the long u."),
  noun("die", "Socke", "Socken", "sock", "ˈzɔkə", "clothes", "Die Socke ist rot.", "The sock is red.", "Mnemonic: Socke is sock plus schwa."),
  noun("die", "Mütze", "Mützen", "cap", "ˈmʏtsə", "clothes", "Die Mütze ist warm.", "The cap is warm.", "Mnemonic: Mütze is a soft winter cap.", ["beanie"]),
  noun("der", "Hut", "Hüte", "hat", "huːt", "clothes", "Der Hut ist schwarz.", "The hat is black.", "Mnemonic: Hut is a brimmed hat, not a beanie."),
  noun("der", "Schal", "Schals", "scarf", "ʃaːl", "clothes", "Der Schal ist weich.", "The scarf is soft.", "Mnemonic: Schal is a shawl around the neck."),
  noun("der", "Handschuh", "Handschuhe", "glove", "ˈhantʃuː", "clothes", "Der Handschuh ist nass.", "The glove is wet.", "Mnemonic: Hand plus Schuh: a shoe for the hand."),
  noun("die", "Brille", "Brillen", "glasses", "ˈbʁɪlə", "clothes", "Die Brille liegt auf dem Tisch.", "The glasses are on the table.", "Mnemonic: Brille is a pair of glasses, one noun.", ["spectacles"]),

  // work
  noun("die", "Arbeit", "Arbeiten", "work", "ˈaʁbaɪt", "work", "Die Arbeit beginnt um acht.", "Work starts at eight.", "Mnemonic: Arbeit is work or a job task."),
  noun("der", "Beruf", "Berufe", "profession", "bəˈʁuːf", "work", "Mein Beruf ist Lehrer.", "My profession is teacher.", "Mnemonic: Beruf is the calling you work in.", ["job"]),
  noun("die", "Firma", "Firmen", "company", "ˈfɪʁma", "work", "Die Firma ist klein.", "The company is small.", "Mnemonic: Firma is a firm."),
  noun("das", "Büro", "Büros", "office", "byˈʁoː", "work", "Das Büro ist hell.", "The office is bright.", "Mnemonic: Büro is bureau; ü is rounded."),
  noun("der", "Computer", "Computer", "computer", "kɔmˈpjuːtɐ", "work", "Der Computer ist neu.", "The computer is new.", "Mnemonic: Computer is a loan; stress -pu-."),
  noun("das", "Handy", "Handys", "mobile phone", "ˈhɛndi", "work", "Das Handy ist in der Tasche.", "The mobile phone is in the bag.", "Mnemonic: German Handy is a mobile, not a handy tool.", ["cell phone", "mobile"]),
  noun("das", "Telefon", "Telefone", "telephone", "teleˈfoːn", "work", "Das Telefon klingelt.", "The telephone is ringing.", "Mnemonic: Telefon; stress the last syllable.", ["phone"]),
  noun("der", "Brief", "Briefe", "letter", "bʁiːf", "work", "Der Brief kommt heute.", "The letter is coming today.", "Mnemonic: Brief is a letter you send, not brief as short."),
  noun("der", "Chef", "Chefs", "boss", "ʃɛf", "work", "Der Chef ist freundlich.", "The boss is friendly.", "Mnemonic: Chef is the boss, not a cook (Koch)."),
  noun("das", "Gehalt", "Gehälter", "salary", "ɡəˈhalt", "work", "Das Gehalt kommt am Monatsersten.", "The salary comes on the first of the month.", "Mnemonic: Gehalt is pay, not Inhalt (contents).", ["wage"]),
  noun("das", "Projekt", "Projekte", "project", "pʁoˈjɛkt", "work", "Das Projekt ist wichtig.", "The project is important.", "Mnemonic: Projekt; j is /j/."),
  noun("der", "Drucker", "Drucker", "printer", "ˈdʁʊkɐ", "work", "Der Drucker ist kaputt.", "The printer is broken.", "Mnemonic: drucken is to print; Drucker is the machine."),

  // school
  noun("die", "Schule", "Schulen", "school", "ˈʃuːlə", "school", "Die Schule beginnt um acht.", "School starts at eight.", "Mnemonic: Schule is school."),
  noun("die", "Klasse", "Klassen", "class", "ˈklasə", "school", "Die Klasse ist groß.", "The class is big.", "Mnemonic: Klasse is a school class or a classroom group."),
  noun("das", "Buch", "Bücher", "book", "buːx", "school", "Das Buch liegt auf dem Tisch.", "The book is on the table.", "Mnemonic: Buch is book; ch is ach-Laut after u."),
  noun("die", "Sprache", "Sprachen", "language", "ˈʃpʁaːxə", "school", "Deutsch ist eine Sprache.", "German is a language.", "Mnemonic: sprechen is to speak; Sprache is the spoken system."),
  noun("das", "Wort", "Wörter", "word", "vɔʁt", "school", "Das Wort ist neu.", "The word is new.", "Mnemonic: Wort is word; Wörter are mixed words, Worte can be sayings."),
  noun("der", "Satz", "Sätze", "sentence", "zats", "school", "Der Satz ist kurz.", "The sentence is short.", "Mnemonic: Satz is a sentence, also a set."),
  noun("die", "Frage", "Fragen", "question", "ˈfʁaːɡə", "school", "Die Frage ist einfach.", "The question is simple.", "Mnemonic: Frage is a question you ask (fragen)."),
  noun("die", "Antwort", "Antworten", "answer", "ˈantvɔʁt", "school", "Die Antwort ist richtig.", "The answer is correct.", "Mnemonic: Antwort is the word that comes back."),
  noun("der", "Stift", "Stifte", "pen", "ʃtɪft", "school", "Der Stift schreibt nicht.", "The pen does not write.", "Mnemonic: Stift is a pen or pencil stick.", ["pencil"]),
  noun("das", "Heft", "Hefte", "exercise book", "hɛft", "school", "Das Heft ist leer.", "The exercise book is empty.", "Mnemonic: Heft is a stapled notebook, not a novel."),
  noun("die", "Prüfung", "Prüfungen", "exam", "ˈpʁyːfʊŋ", "school", "Die Prüfung ist schwer.", "The exam is hard.", "Mnemonic: prüfen is to test; Prüfung is the test.", ["test"]),
  noun("die", "Hausaufgabe", "Hausaufgaben", "homework", "ˈhaʊsʔaʊfˌɡaːbə", "school", "Die Hausaufgabe ist fertig.", "The homework is done.", "Mnemonic: Haus plus Aufgabe: the task for home."),
  noun("die", "Universität", "Universitäten", "university", "ʔunivɛʁziˈtɛːt", "school", "Die Universität ist alt.", "The university is old.", "Mnemonic: long word; stress the last syllable.", ["uni"]),
];

const VERBS: CoreLexeme[] = [
  verb("sein", "to be", "zaɪn", "verbs", { ich: "bin", du: "bist", er: "ist", wir: "sind", ihr: "seid", sie: "sind" }, "Ich bin hier.", "I am here.", "Mnemonic: sein jumps: bin, bist, ist, sind, seid, sind.", false),
  verb("haben", "to have", "ˈhaːbn̩", "verbs", { ich: "habe", du: "hast", er: "hat", wir: "haben", ihr: "habt", sie: "haben" }, "Ich habe Zeit.", "I have time.", "Mnemonic: haben keeps ha-; du/er cut to hast/hat.", true),
  verb("werden", "to become", "ˈveːɐ̯dn̩", "verbs", { ich: "werde", du: "wirst", er: "wird", wir: "werden", ihr: "werdet", sie: "werden" }, "Es wird kalt.", "It is becoming cold.", "Mnemonic: werden is become; later it also builds future.", false),
  verb("können", "can / to be able to", "ˈkœnən", "verbs", { ich: "kann", du: "kannst", er: "kann", wir: "können", ihr: "könnt", sie: "können" }, "Ich kann Deutsch.", "I can speak German.", "Mnemonic: modal; ich/er share kann.", false, ["can"]),
  verb("müssen", "must / to have to", "ˈmʏsn̩", "verbs", { ich: "muss", du: "musst", er: "muss", wir: "müssen", ihr: "müsst", sie: "müssen" }, "Ich muss gehen.", "I have to go.", "Mnemonic: modal; muss has no umlaut in ich/du/er.", false, ["must"]),
  verb("wollen", "to want", "ˈvɔlən", "verbs", { ich: "will", du: "willst", er: "will", wir: "wollen", ihr: "wollt", sie: "wollen" }, "Ich will Wasser.", "I want water.", "Mnemonic: modal; ich/er use will, not wolle.", false),
  verb("heißen", "to be called", "ˈhaɪsn̩", "verbs", { ich: "heiße", du: "heißt", er: "heißt", wir: "heißen", ihr: "heißt", sie: "heißen" }, "Ich heiße Anna.", "I am called Anna.", "Mnemonic: heißen is the name-verb, not to be named as a title.", false),
  verb("wohnen", "to live (somewhere)", "ˈvoːnən", "verbs", { ich: "wohne", du: "wohnst", er: "wohnt", wir: "wohnen", ihr: "wohnt", sie: "wohnen" }, "Ich wohne in Berlin.", "I live in Berlin.", "Mnemonic: wohnen is live-at-an-address; leben is broader live.", false),
  verb("kommen", "to come", "ˈkɔmən", "verbs", { ich: "komme", du: "kommst", er: "kommt", wir: "kommen", ihr: "kommt", sie: "kommen" }, "Ich komme aus Spanien.", "I come from Spain.", "Mnemonic: kommen is come; aus plus a country.", false),
  verb("gehen", "to go / to walk", "ˈɡeːən", "verbs", { ich: "gehe", du: "gehst", er: "geht", wir: "gehen", ihr: "geht", sie: "gehen" }, "Ich gehe nach Hause.", "I am going home.", "Mnemonic: gehen is go on foot; h only lengthens e.", false, ["walk"]),
  verb("fahren", "to go (by vehicle)", "ˈfaːʁən", "verbs", { ich: "fahre", du: "fährst", er: "fährt", wir: "fahren", ihr: "fahrt", sie: "fahren" }, "Ich fahre nach Köln.", "I am going to Cologne.", "Mnemonic: fahren is travel by vehicle; du/er take ä.", false),
  verb("machen", "to do / to make", "ˈmaxn̩", "verbs", { ich: "mache", du: "machst", er: "macht", wir: "machen", ihr: "macht", sie: "machen" }, "Ich mache das.", "I am doing that.", "Mnemonic: machen is the all-purpose do/make.", true, ["do", "make"]),
  verb("lernen", "to learn", "ˈlɛʁnən", "verbs", { ich: "lerne", du: "lernst", er: "lernt", wir: "lernen", ihr: "lernt", sie: "lernen" }, "Ich lerne Deutsch.", "I am learning German.", "Mnemonic: lernen is learn; studieren is a university subject.", true),
  verb("sprechen", "to speak", "ˈʃpʁɛçn̩", "verbs", { ich: "spreche", du: "sprichst", er: "spricht", wir: "sprechen", ihr: "sprecht", sie: "sprechen" }, "Ich spreche Deutsch.", "I speak German.", "Mnemonic: e to i in du/er: sprichst, spricht.", true),
  verb("essen", "to eat", "ˈɛsn̩", "verbs", { ich: "esse", du: "isst", er: "isst", wir: "essen", ihr: "esst", sie: "essen" }, "Ich esse Brot.", "I eat bread.", "Mnemonic: essen changes to isst in du/er.", true),
  verb("trinken", "to drink", "ˈtʁɪŋkn̩", "verbs", { ich: "trinke", du: "trinkst", er: "trinkt", wir: "trinken", ihr: "trinkt", sie: "trinken" }, "Ich trinke Wasser.", "I drink water.", "Mnemonic: trinken is drink; ng is /ŋ/.", true),
  verb("kaufen", "to buy", "ˈkaʊfn̩", "verbs", { ich: "kaufe", du: "kaufst", er: "kauft", wir: "kaufen", ihr: "kauft", sie: "kaufen" }, "Ich kaufe Brot.", "I buy bread.", "Mnemonic: kaufen is buy; einkaufen is go shopping.", true),
  verb("sehen", "to see", "ˈzeːən", "verbs", { ich: "sehe", du: "siehst", er: "sieht", wir: "sehen", ihr: "seht", sie: "sehen" }, "Ich sehe den Zug.", "I see the train.", "Mnemonic: sehen: du/er take ie (siehst, sieht).", true),
  verb("hören", "to hear", "ˈhøːʁən", "verbs", { ich: "höre", du: "hörst", er: "hört", wir: "hören", ihr: "hört", sie: "hören" }, "Ich höre Musik.", "I hear music.", "Mnemonic: hören is hear; ö is rounded e.", true),
  verb("lesen", "to read", "ˈleːzn̩", "verbs", { ich: "lese", du: "liest", er: "liest", wir: "lesen", ihr: "lest", sie: "lesen" }, "Ich lese das Buch.", "I read the book.", "Mnemonic: lesen: du/er take ie (liest).", true),
  verb("schreiben", "to write", "ˈʃʁaɪbn̩", "verbs", { ich: "schreibe", du: "schreibst", er: "schreibt", wir: "schreiben", ihr: "schreibt", sie: "schreiben" }, "Ich schreibe einen Brief.", "I write a letter.", "Mnemonic: schreiben starts with schr; ei as in mine.", true),
  verb("verstehen", "to understand", "fɛɐ̯ˈʃteːən", "verbs", { ich: "verstehe", du: "verstehst", er: "versteht", wir: "verstehen", ihr: "versteht", sie: "verstehen" }, "Ich verstehe das nicht.", "I do not understand that.", "Mnemonic: verstehen is understand; stehen hides inside it.", true),
  verb("wissen", "to know (a fact)", "ˈvɪsn̩", "verbs", { ich: "weiß", du: "weißt", er: "weiß", wir: "wissen", ihr: "wisst", sie: "wissen" }, "Ich weiß das.", "I know that.", "Mnemonic: wissen is fact-know; kennen is know a person.", true),
  verb("kennen", "to know (a person/place)", "ˈkɛnən", "verbs", { ich: "kenne", du: "kennst", er: "kennt", wir: "kennen", ihr: "kennt", sie: "kennen" }, "Ich kenne den Weg.", "I know the way.", "Mnemonic: kennen is be-acquainted-with.", true),
  verb("finden", "to find", "ˈfɪndn̩", "verbs", { ich: "finde", du: "findest", er: "findet", wir: "finden", ihr: "findet", sie: "finden" }, "Ich finde den Schlüssel.", "I find the key.", "Mnemonic: finden is find; also used for I think that (ich finde).", true),
  verb("suchen", "to search / to look for", "ˈzuːxn̩", "verbs", { ich: "suche", du: "suchst", er: "sucht", wir: "suchen", ihr: "sucht", sie: "suchen" }, "Ich suche die Tasche.", "I am looking for the bag.", "Mnemonic: suchen is look for, with a direct object.", true, ["look for"]),
  verb("brauchen", "to need", "ˈbʁaʊxn̩", "verbs", { ich: "brauche", du: "brauchst", er: "braucht", wir: "brauchen", ihr: "braucht", sie: "brauchen" }, "Ich brauche Hilfe.", "I need help.", "Mnemonic: brauchen is need; not brauchen as use in older style.", true),
  verb("nehmen", "to take", "ˈneːmən", "verbs", { ich: "nehme", du: "nimmst", er: "nimmt", wir: "nehmen", ihr: "nehmt", sie: "nehmen" }, "Ich nehme das.", "I will take that.", "Mnemonic: nehmen: du/er jump to nimmst, nimmt.", true),
  verb("geben", "to give", "ˈɡeːbn̩", "verbs", { ich: "gebe", du: "gibst", er: "gibt", wir: "geben", ihr: "gebt", sie: "geben" }, "Ich gebe dir das Buch.", "I give you the book.", "Mnemonic: geben: du/er use i (gibst, gibt).", true),
  verb("bleiben", "to stay", "ˈblaɪbn̩", "verbs", { ich: "bleibe", du: "bleibst", er: "bleibt", wir: "bleiben", ihr: "bleibt", sie: "bleiben" }, "Ich bleibe hier.", "I am staying here.", "Mnemonic: bleiben is stay / remain.", false),
  verb("stehen", "to stand", "ˈʃteːən", "verbs", { ich: "stehe", du: "stehst", er: "steht", wir: "stehen", ihr: "steht", sie: "stehen" }, "Ich stehe am Fenster.", "I am standing at the window.", "Mnemonic: stehen is stand; also used for things located upright.", false),
  verb("sitzen", "to sit", "ˈzɪtsn̩", "verbs", { ich: "sitze", du: "sitzt", er: "sitzt", wir: "sitzen", ihr: "sitzt", sie: "sitzen" }, "Ich sitze auf dem Stuhl.", "I am sitting on the chair.", "Mnemonic: sitzen is sit; z is /ts/.", false),
  verb("liegen", "to lie / be lying", "ˈliːɡn̩", "verbs", { ich: "liege", du: "liegst", er: "liegt", wir: "liegen", ihr: "liegt", sie: "liegen" }, "Das Buch liegt auf dem Tisch.", "The book is lying on the table.", "Mnemonic: liegen is be-horizontal, not lügen (to tell a lie).", false),
  verb("schlafen", "to sleep", "ˈʃlaːfn̩", "verbs", { ich: "schlafe", du: "schläfst", er: "schläft", wir: "schlafen", ihr: "schlaft", sie: "schlafen" }, "Ich schlafe lange.", "I sleep a long time.", "Mnemonic: schlafen: du/er take ä.", false),
  verb("arbeiten", "to work", "ˈaʁbaɪtn̩", "verbs", { ich: "arbeite", du: "arbeitest", er: "arbeitet", wir: "arbeiten", ihr: "arbeitet", sie: "arbeiten" }, "Ich arbeite im Büro.", "I work in the office.", "Mnemonic: arbeiten is work; du adds -est after t.", false),
  verb("spielen", "to play", "ˈʃpiːlən", "verbs", { ich: "spiele", du: "spielst", er: "spielt", wir: "spielen", ihr: "spielt", sie: "spielen" }, "Ich spiele Fußball.", "I play football.", "Mnemonic: spielen takes a game as object.", true),
  verb("kochen", "to cook", "ˈkɔxn̩", "verbs", { ich: "koche", du: "kochst", er: "kocht", wir: "kochen", ihr: "kocht", sie: "kochen" }, "Ich koche Suppe.", "I cook soup.", "Mnemonic: kochen is cook; ch is ach-Laut.", true),
  verb("öffnen", "to open", "ˈœfnən", "verbs", { ich: "öffne", du: "öffnest", er: "öffnet", wir: "öffnen", ihr: "öffnet", sie: "öffnen" }, "Ich öffne die Tür.", "I open the door.", "Mnemonic: öffnen is open; ö at the start.", true),
  verb("schließen", "to close", "ˈʃliːsn̩", "verbs", { ich: "schließe", du: "schließt", er: "schließt", wir: "schließen", ihr: "schließt", sie: "schließen" }, "Ich schließe das Fenster.", "I close the window.", "Mnemonic: schließen is close; ß after ie.", true),
  verb("beginnen", "to begin", "bəˈɡɪnən", "verbs", { ich: "beginne", du: "beginnst", er: "beginnt", wir: "beginnen", ihr: "beginnt", sie: "beginnen" }, "Der Kurs beginnt um zehn.", "The course begins at ten.", "Mnemonic: beginnen is begin.", true),
  verb("helfen", "to help", "ˈhɛlfn̩", "verbs", { ich: "helfe", du: "hilfst", er: "hilft", wir: "helfen", ihr: "helft", sie: "helfen" }, "Ich helfe dir.", "I help you.", "Mnemonic: helfen takes a dative person, not accusative.", false),
  verb("fragen", "to ask", "ˈfʁaːɡn̩", "verbs", { ich: "frage", du: "fragst", er: "fragt", wir: "fragen", ihr: "fragt", sie: "fragen" }, "Ich frage den Lehrer.", "I ask the teacher.", "Mnemonic: fragen takes the person you ask.", true),
  verb("antworten", "to answer", "ˈantvɔʁtn̩", "verbs", { ich: "antworte", du: "antwortest", er: "antwortet", wir: "antworten", ihr: "antwortet", sie: "antworten" }, "Ich antworte auf die Frage.", "I answer the question.", "Mnemonic: antworten often takes auf plus the question.", false),
  verb("sagen", "to say", "ˈzaːɡn̩", "verbs", { ich: "sage", du: "sagst", er: "sagt", wir: "sagen", ihr: "sagt", sie: "sagen" }, "Ich sage das Wort.", "I say the word.", "Mnemonic: sagen is say; s is /z/.", true),
  verb("erzählen", "to tell", "ɛɐ̯ˈtsɛːlən", "verbs", { ich: "erzähle", du: "erzählst", er: "erzählt", wir: "erzählen", ihr: "erzählt", sie: "erzählen" }, "Ich erzähle eine Geschichte.", "I tell a story.", "Mnemonic: erzählen is tell a story, not just say a word.", true),
  verb("denken", "to think", "ˈdɛŋkn̩", "verbs", { ich: "denke", du: "denkst", er: "denkt", wir: "denken", ihr: "denkt", sie: "denken" }, "Ich denke an dich.", "I am thinking of you.", "Mnemonic: denken an is think of; not a bare object.", false),
  verb("glauben", "to believe", "ˈɡlaʊbn̩", "verbs", { ich: "glaube", du: "glaubst", er: "glaubt", wir: "glauben", ihr: "glaubt", sie: "glauben" }, "Ich glaube das.", "I believe that.", "Mnemonic: glauben can take a that-clause or a dative person.", true),
  verb("lieben", "to love", "ˈliːbn̩", "verbs", { ich: "liebe", du: "liebst", er: "liebt", wir: "lieben", ihr: "liebt", sie: "lieben" }, "Ich liebe diese Stadt.", "I love this city.", "Mnemonic: lieben is love; long i.", true),
  verb("mögen", "to like", "ˈmøːɡn̩", "verbs", { ich: "mag", du: "magst", er: "mag", wir: "mögen", ihr: "mögt", sie: "mögen" }, "Ich mag Kaffee.", "I like coffee.", "Mnemonic: mögen is like; ich/er use mag.", true),
  verb("dürfen", "may / to be allowed to", "ˈdʏʁfn̩", "verbs", { ich: "darf", du: "darfst", er: "darf", wir: "dürfen", ihr: "dürft", sie: "dürfen" }, "Ich darf hier bleiben.", "I am allowed to stay here.", "Mnemonic: modal; ich/er use darf.", false, ["may"]),
  verb("sollen", "ought to / to be supposed to", "ˈzɔlən", "verbs", { ich: "soll", du: "sollst", er: "soll", wir: "sollen", ihr: "sollt", sie: "sollen" }, "Ich soll lernen.", "I am supposed to study.", "Mnemonic: modal; sollen is duty from outside.", false),
  verb("bringen", "to bring", "ˈbʁɪŋən", "verbs", { ich: "bringe", du: "bringst", er: "bringt", wir: "bringen", ihr: "bringt", sie: "bringen" }, "Ich bringe das Buch.", "I bring the book.", "Mnemonic: bringen is bring toward the listener.", true),
  verb("holen", "to fetch", "ˈhoːlən", "verbs", { ich: "hole", du: "holst", er: "holt", wir: "holen", ihr: "holt", sie: "holen" }, "Ich hole Wasser.", "I fetch water.", "Mnemonic: holen is go-and-get.", true),
  verb("treffen", "to meet", "ˈtʁɛfn̩", "verbs", { ich: "treffe", du: "triffst", er: "trifft", wir: "treffen", ihr: "trefft", sie: "treffen" }, "Ich treffe einen Freund.", "I meet a friend.", "Mnemonic: treffen: du/er take i (triffst, trifft).", true),
  verb("warten", "to wait", "ˈvaʁtn̩", "verbs", { ich: "warte", du: "wartest", er: "wartet", wir: "warten", ihr: "wartet", sie: "warten" }, "Ich warte hier.", "I am waiting here.", "Mnemonic: warten auf is wait for; bare warten is wait.", false),
  verb("laufen", "to run", "ˈlaʊfn̩", "verbs", { ich: "laufe", du: "läufst", er: "läuft", wir: "laufen", ihr: "lauft", sie: "laufen" }, "Ich laufe zum Bahnhof.", "I run to the station.", "Mnemonic: laufen: du/er take ä; also everyday walk in some regions.", false),
  verb("fliegen", "to fly", "ˈfliːɡn̩", "verbs", { ich: "fliege", du: "fliegst", er: "fliegt", wir: "fliegen", ihr: "fliegt", sie: "fliegen" }, "Ich fliege nach Rom.", "I fly to Rome.", "Mnemonic: fliegen is fly.", false),
  verb("schwimmen", "to swim", "ˈʃvɪmən", "verbs", { ich: "schwimme", du: "schwimmst", er: "schwimmt", wir: "schwimmen", ihr: "schwimmt", sie: "schwimmen" }, "Ich schwimme im See.", "I swim in the lake.", "Mnemonic: schwimmen is swim; schw is /ʃv/.", false),
  verb("tanzen", "to dance", "ˈtantsn̩", "verbs", { ich: "tanze", du: "tanzt", er: "tanzt", wir: "tanzen", ihr: "tanzt", sie: "tanzen" }, "Ich tanze gern.", "I like to dance.", "Mnemonic: tanzen is dance; z is /ts/.", false),
  verb("singen", "to sing", "ˈzɪŋən", "verbs", { ich: "singe", du: "singst", er: "singt", wir: "singen", ihr: "singt", sie: "singen" }, "Ich singe ein Lied.", "I sing a song.", "Mnemonic: singen is sing; can take a song as object.", true),
  verb("zahlen", "to pay", "ˈtsaːlən", "verbs", { ich: "zahle", du: "zahlst", er: "zahlt", wir: "zahlen", ihr: "zahlt", sie: "zahlen" }, "Ich zahle die Rechnung.", "I pay the bill.", "Mnemonic: zahlen is pay money; zählen with ä is to count.", true),
  verb("kosten", "to cost", "ˈkɔstn̩", "verbs", { ich: "koste", du: "kostest", er: "kostet", wir: "kosten", ihr: "kostet", sie: "kosten" }, "Das kostet fünf Euro.", "That costs five euros.", "Mnemonic: kosten is cost; the thing is the subject.", true),
  verb("putzen", "to clean", "ˈpʊtsn̩", "verbs", { ich: "putze", du: "putzt", er: "putzt", wir: "putzen", ihr: "putzt", sie: "putzen" }, "Ich putze das Fenster.", "I clean the window.", "Mnemonic: putzen is clean a surface.", true),
  verb("waschen", "to wash", "ˈvaʃn̩", "verbs", { ich: "wasche", du: "wäschst", er: "wäscht", wir: "waschen", ihr: "wascht", sie: "waschen" }, "Ich wasche das Hemd.", "I wash the shirt.", "Mnemonic: waschen: du/er take ä.", true),
  verb("duschen", "to shower", "ˈdʊʃn̩", "verbs", { ich: "dusche", du: "duschst", er: "duscht", wir: "duschen", ihr: "duscht", sie: "duschen" }, "Ich dusche am Morgen.", "I shower in the morning.", "Mnemonic: duschen is take a shower.", false),
  verb("anrufen", "to call (by phone)", "ˈanˌʁuːfn̩", "verbs", { ich: "rufe an", du: "rufst an", er: "ruft an", wir: "rufen an", ihr: "ruft an", sie: "rufen an" }, "Ich rufe dich an.", "I will call you.", "Mnemonic: separable: rufe … an.", true),
  verb("schicken", "to send", "ˈʃɪkn̩", "verbs", { ich: "schicke", du: "schickst", er: "schickt", wir: "schicken", ihr: "schickt", sie: "schicken" }, "Ich schicke eine E-Mail.", "I send an email.", "Mnemonic: schicken is send.", true),
  verb("bekommen", "to receive / to get", "bəˈkɔmən", "verbs", { ich: "bekomme", du: "bekommst", er: "bekommt", wir: "bekommen", ihr: "bekommt", sie: "bekommen" }, "Ich bekomme einen Brief.", "I receive a letter.", "Mnemonic: bekommen is get, not become (werden).", true, ["get"]),
  verb("zeigen", "to show", "ˈtsaɪɡn̩", "verbs", { ich: "zeige", du: "zeigst", er: "zeigt", wir: "zeigen", ihr: "zeigt", sie: "zeigen" }, "Ich zeige den Weg.", "I show the way.", "Mnemonic: zeigen is show; z is /ts/.", true),
  verb("erklären", "to explain", "ɛɐ̯ˈklɛːʁən", "verbs", { ich: "erkläre", du: "erklärst", er: "erklärt", wir: "erklären", ihr: "erklärt", sie: "erklären" }, "Ich erkläre das Wort.", "I explain the word.", "Mnemonic: erklären is explain, make clear.", true),
  verb("wiederholen", "to repeat", "ˈviːdɐhoːlən", "verbs", { ich: "wiederhole", du: "wiederholst", er: "wiederholt", wir: "wiederholen", ihr: "wiederholt", sie: "wiederholen" }, "Ich wiederhole den Satz.", "I repeat the sentence.", "Mnemonic: wieder plus holen: fetch it again.", true),
  verb("studieren", "to study (a subject)", "ʃtuˈdiːʁən", "verbs", { ich: "studiere", du: "studierst", er: "studiert", wir: "studieren", ihr: "studiert", sie: "studieren" }, "Ich studiere in Berlin.", "I study in Berlin.", "Mnemonic: studieren is campus study, not everyday lernen.", true),
  verb("einkaufen", "to shop / to go shopping", "ˈaɪnˌkaʊfn̩", "verbs", { ich: "kaufe ein", du: "kaufst ein", er: "kauft ein", wir: "kaufen ein", ihr: "kauft ein", sie: "kaufen ein" }, "Ich kaufe im Supermarkt ein.", "I shop at the supermarket.", "Mnemonic: separable: kaufe … ein.", false, ["shop"]),
  verb("bestellen", "to order", "bəˈʃtɛlən", "verbs", { ich: "bestelle", du: "bestellst", er: "bestellt", wir: "bestellen", ihr: "bestellt", sie: "bestellen" }, "Ich bestelle einen Kaffee.", "I order a coffee.", "Mnemonic: bestellen is order food or goods.", true),
  verb("tragen", "to carry / to wear", "ˈtʁaːɡn̩", "verbs", { ich: "trage", du: "trägst", er: "trägt", wir: "tragen", ihr: "tragt", sie: "tragen" }, "Ich trage eine Jacke.", "I am wearing a jacket.", "Mnemonic: tragen is carry or wear; du/er take ä.", true, ["wear"]),
  verb("verlieren", "to lose", "fɛɐ̯ˈliːʁən", "verbs", { ich: "verliere", du: "verlierst", er: "verliert", wir: "verlieren", ihr: "verliert", sie: "verlieren" }, "Ich verliere den Schlüssel.", "I lose the key.", "Mnemonic: verlieren is lose; not related to lieben.", true),
  verb("gewinnen", "to win", "ɡəˈvɪnən", "verbs", { ich: "gewinne", du: "gewinnst", er: "gewinnt", wir: "gewinnen", ihr: "gewinnt", sie: "gewinnen" }, "Wir gewinnen das Spiel.", "We win the game.", "Mnemonic: gewinnen is win.", true),
  verb("vergessen", "to forget", "fɛɐ̯ˈɡɛsn̩", "verbs", { ich: "vergesse", du: "vergisst", er: "vergisst", wir: "vergessen", ihr: "vergesst", sie: "vergessen" }, "Ich vergesse den Namen.", "I forget the name.", "Mnemonic: vergessen: du/er take i (vergisst).", true),
  verb("besuchen", "to visit", "bəˈzuːxn̩", "verbs", { ich: "besuche", du: "besuchst", er: "besucht", wir: "besuchen", ihr: "besucht", sie: "besuchen" }, "Ich besuche meine Tante.", "I visit my aunt.", "Mnemonic: besuchen is visit a person or a place.", true),
  verb("leben", "to live", "ˈleːbn̩", "verbs", { ich: "lebe", du: "lebst", er: "lebt", wir: "leben", ihr: "lebt", sie: "leben" }, "Ich lebe in Deutschland.", "I live in Germany.", "Mnemonic: leben is be-alive / live; wohnen is reside.", false),
];

const ADJECTIVES: CoreLexeme[] = [
  word("adj", "gut", "good", "ɡuːt", "quality", "Das Brot ist gut.", "The bread is good.", "Mnemonic: gut is good; u is long."),
  word("adj", "schlecht", "bad", "ʃlɛçt", "quality", "Das Wetter ist schlecht.", "The weather is bad.", "Mnemonic: schlecht is bad; ich-Laut in the middle."),
  word("adj", "groß", "big / tall", "ɡʁoːs", "quality", "Das Haus ist groß.", "The house is big.", "Mnemonic: groß is big; ß after long o.", ["large"]),
  word("adj", "klein", "small", "klaɪn", "quality", "Die Wohnung ist klein.", "The apartment is small.", "Mnemonic: klein is small; ei as in mine."),
  word("adj", "neu", "new", "nɔʏ", "quality", "Das Auto ist neu.", "The car is new.", "Mnemonic: neu is new; eu as in Deutsch."),
  word("adj", "alt", "old", "alt", "quality", "Der Mann ist alt.", "The man is old.", "Mnemonic: alt is old."),
  word("adj", "jung", "young", "jʊŋ", "quality", "Das Kind ist jung.", "The child is young.", "Mnemonic: jung is young; j as English y."),
  word("adj", "schön", "beautiful / nice", "ʃøːn", "quality", "Die Stadt ist schön.", "The city is beautiful.", "Mnemonic: schön is nice to look at; ö is rounded.", ["nice"]),
  word("adj", "lang", "long", "laŋ", "quality", "Der Weg ist lang.", "The way is long.", "Mnemonic: lang is long; ng is /ŋ/."),
  word("adj", "kurz", "short", "kʊʁts", "quality", "Die Pause ist kurz.", "The break is short.", "Mnemonic: kurz is short; z is /ts/."),
  word("adj", "schnell", "fast", "ʃnɛl", "quality", "Der Zug ist schnell.", "The train is fast.", "Mnemonic: schnell is fast; doubled n and l."),
  word("adj", "langsam", "slow", "ˈlaŋzaːm", "quality", "Der Bus ist langsam.", "The bus is slow.", "Mnemonic: langsam is long-sam: taking a long time."),
  word("adj", "teuer", "expensive", "ˈtɔʏɐ", "quality", "Das Hotel ist teuer.", "The hotel is expensive.", "Mnemonic: teuer is pricey; eu as in Deutsch."),
  word("adj", "billig", "cheap", "ˈbɪlɪç", "quality", "Das Brot ist billig.", "The bread is cheap.", "Mnemonic: billig is cheap; -ig is /ɪç/."),
  word("adj", "leicht", "easy / light", "laɪçt", "quality", "Die Frage ist leicht.", "The question is easy.", "Mnemonic: leicht is easy or not heavy."),
  word("adj", "schwer", "heavy / difficult", "ʃveːɐ̯", "quality", "Der Koffer ist schwer.", "The suitcase is heavy.", "Mnemonic: schwer is heavy and also hard."),
  word("adj", "warm", "warm", "vaʁm", "quality", "Die Suppe ist warm.", "The soup is warm.", "Mnemonic: warm is warm; w is /v/."),
  word("adj", "kalt", "cold", "kalt", "quality", "Das Wasser ist kalt.", "The water is cold.", "Mnemonic: kalt is cold."),
  word("adj", "heiß", "hot", "haɪs", "quality", "Der Kaffee ist heiß.", "The coffee is hot.", "Mnemonic: heiß is hot; ß after ei."),
  word("adj", "kühl", "cool", "kyːl", "quality", "Der Keller ist kühl.", "The basement is cool.", "Mnemonic: kühl is cool to the touch."),
  word("adj", "hell", "bright", "hɛl", "quality", "Das Zimmer ist hell.", "The room is bright.", "Mnemonic: hell is bright light, not English hell."),
  word("adj", "dunkel", "dark", "ˈdʊŋkl̩", "quality", "Die Nacht ist dunkel.", "The night is dark.", "Mnemonic: dunkel is dark."),
  word("adj", "offen", "open", "ˈɔfn̩", "quality", "Die Tür ist offen.", "The door is open.", "Mnemonic: offen is open, the state after öffnen."),
  word("adj", "geschlossen", "closed", "ɡəˈʃlɔsn̩", "quality", "Das Geschäft ist geschlossen.", "The shop is closed.", "Mnemonic: past form of schließen used as an adjective."),
  word("adj", "voll", "full", "fɔl", "quality", "Die Tasche ist voll.", "The bag is full.", "Mnemonic: voll is full."),
  word("adj", "leer", "empty", "leːɐ̯", "quality", "Der Teller ist leer.", "The plate is empty.", "Mnemonic: leer is empty; long e."),
  word("adj", "früh", "early", "fʁyː", "quality", "Ich bin früh da.", "I am there early.", "Mnemonic: früh is early; ü is long."),
  word("adj", "spät", "late", "ʃpɛːt", "quality", "Es ist spät.", "It is late.", "Mnemonic: spät is late; ä is long."),
  word("adj", "richtig", "correct / right", "ˈʁɪçtɪç", "quality", "Die Antwort ist richtig.", "The answer is correct.", "Mnemonic: richtig is right; both -ig sounds are ich-Laut.", ["right"]),
  word("adj", "falsch", "wrong", "falʃ", "quality", "Das Wort ist falsch.", "The word is wrong.", "Mnemonic: falsch is false / wrong."),
  word("adj", "wichtig", "important", "ˈvɪçtɪç", "quality", "Der Termin ist wichtig.", "The appointment is important.", "Mnemonic: wichtig is weighty in meaning."),
  word("adj", "einfach", "simple / easy", "ˈaɪnfax", "quality", "Die Aufgabe ist einfach.", "The task is simple.", "Mnemonic: ein plus fach: one-fold, not complicated."),
  word("adj", "schwierig", "difficult", "ˈʃviːʁɪç", "quality", "Die Prüfung ist schwierig.", "The exam is difficult.", "Mnemonic: schwierig is hard in the mental sense."),
  word("adj", "interessant", "interesting", "ɪntəʁɛˈsant", "quality", "Das Buch ist interessant.", "The book is interesting.", "Mnemonic: loan; stress the last syllable."),
  word("adj", "freundlich", "friendly", "ˈfʁɔʏntlɪç", "quality", "Der Nachbar ist freundlich.", "The neighbor is friendly.", "Mnemonic: Freund plus -lich: friend-like."),
  word("adj", "nett", "kind / nice", "nɛt", "quality", "Die Kollegin ist nett.", "The colleague is nice.", "Mnemonic: nett is pleasantly nice."),
  word("adj", "müde", "tired", "ˈmyːdə", "quality", "Ich bin müde.", "I am tired.", "Mnemonic: müde is tired; ü is long."),
  word("adj", "krank", "ill", "kʁaŋk", "quality", "Ich bin krank.", "I am ill.", "Mnemonic: krank is ill; Krankenhaus hides it.", ["sick"]),
  word("adj", "gesund", "healthy", "ɡəˈzʊnt", "quality", "Das Essen ist gesund.", "The food is healthy.", "Mnemonic: gesund is healthy; final d as t."),
  word("adj", "hungrig", "hungry", "ˈhʊŋʁɪç", "quality", "Ich bin hungrig.", "I am hungry.", "Mnemonic: Hunger plus -ig."),
  word("adj", "durstig", "thirsty", "ˈdʊʁstɪç", "quality", "Ich bin durstig.", "I am thirsty.", "Mnemonic: Durst plus -ig."),
  word("adj", "froh", "glad", "fʁoː", "quality", "Ich bin froh.", "I am glad.", "Mnemonic: froh is glad; h lengthens o."),
  word("adj", "traurig", "sad", "ˈtʁaʊʁɪç", "quality", "Das Kind ist traurig.", "The child is sad.", "Mnemonic: traurig is sad."),
  word("adj", "laut", "loud", "laʊt", "quality", "Die Musik ist laut.", "The music is loud.", "Mnemonic: laut is loud; au as in house."),
  word("adj", "leise", "quiet", "ˈlaɪzə", "quality", "Bitte sei leise.", "Please be quiet.", "Mnemonic: leise is quiet, not lazy."),
  word("adj", "sauber", "clean", "ˈzaʊbɐ", "quality", "Die Küche ist sauber.", "The kitchen is clean.", "Mnemonic: sauber is clean."),
  word("adj", "schmutzig", "dirty", "ˈʃmʊtsɪç", "quality", "Der Teppich ist schmutzig.", "The carpet is dirty.", "Mnemonic: Schmutz plus -ig."),
  word("adj", "frei", "free", "fʁaɪ", "quality", "Der Stuhl ist frei.", "The chair is free.", "Mnemonic: frei is free / available."),
  word("adj", "fertig", "finished / ready", "ˈfɛʁtɪç", "quality", "Ich bin fertig.", "I am finished.", "Mnemonic: fertig is done; -ig is /ɪç/.", ["ready"]),
  word("adj", "möglich", "possible", "ˈmøːklɪç", "quality", "Das ist möglich.", "That is possible.", "Mnemonic: möglich is possible; ö is rounded."),
];

const FUNCTION_WORDS: CoreLexeme[] = [
  // adverbs
  word("adv", "hier", "here", "hiːɐ̯", "function", "Ich bin hier.", "I am here.", "Mnemonic: hier is here."),
  word("adv", "dort", "there", "dɔʁt", "function", "Der Bahnhof ist dort.", "The station is there.", "Mnemonic: dort is a pointed there, farther than da."),
  word("adv", "da", "there / here", "daː", "function", "Das Buch ist da.", "The book is there.", "Mnemonic: da is a loose here/there."),
  word("adv", "jetzt", "now", "jɛtst", "time", "Ich gehe jetzt.", "I am going now.", "Mnemonic: jetzt is now; j as English y."),
  word("adv", "heute", "today", "ˈhɔʏtə", "time", "Heute lerne ich.", "Today I study.", "Mnemonic: heute is today; eu as in Deutsch."),
  word("adv", "morgen", "tomorrow", "ˈmɔʁɡn̩", "time", "Bis morgen!", "See you tomorrow!", "Mnemonic: lowercase morgen is tomorrow; noun Morgen is morning.", [], "tomorrow"),
  word("adv", "gestern", "yesterday", "ˈɡɛstɐn", "time", "Gestern war ich müde.", "Yesterday I was tired.", "Mnemonic: gestern is yesterday."),
  word("adv", "bald", "soon", "balt", "time", "Der Bus kommt bald.", "The bus is coming soon.", "Mnemonic: bald is soon; final d as t."),
  word("adv", "immer", "always", "ˈɪmɐ", "time", "Ich lerne immer.", "I always study.", "Mnemonic: immer is always."),
  word("adv", "nie", "never", "niː", "time", "Ich bin nie krank.", "I am never ill.", "Mnemonic: nie is never; long i."),
  word("adv", "oft", "often", "ɔft", "time", "Ich kaufe oft Brot.", "I often buy bread.", "Mnemonic: oft is often."),
  word("adv", "manchmal", "sometimes", "ˈmançmaːl", "time", "Manchmal regnet es.", "Sometimes it rains.", "Mnemonic: manches Mal packed into one word."),
  word("adv", "auch", "also / too", "aʊx", "function", "Ich komme auch.", "I am coming too.", "Mnemonic: auch is also; ach-Laut."),
  word("adv", "nur", "only", "nuːɐ̯", "function", "Ich habe nur Wasser.", "I only have water.", "Mnemonic: nur is only."),
  word("adv", "sehr", "very", "zeːɐ̯", "function", "Das ist sehr gut.", "That is very good.", "Mnemonic: sehr is very; s is /z/."),
  word("adv", "so", "so / like this", "zoː", "function", "Es ist so kalt.", "It is so cold.", "Mnemonic: so is so."),
  word("adv", "dann", "then", "dan", "time", "Erst Kaffee, dann Arbeit.", "First coffee, then work.", "Mnemonic: dann is then in a sequence."),
  word("adv", "noch", "still / yet", "nɔx", "function", "Ich habe noch Zeit.", "I still have time.", "Mnemonic: noch is still; ach-Laut."),
  word("adv", "schon", "already", "ʃoːn", "function", "Der Zug ist schon da.", "The train is already here.", "Mnemonic: schon is already, not schön (beautiful)."),
  word("adv", "nicht", "not", "nɪçt", "function", "Ich verstehe das nicht.", "I do not understand that.", "Mnemonic: nicht is the sentence not; kein is not-a for nouns."),
  word("adv", "gern", "gladly / like to", "ɡɛʁn", "function", "Ich trinke gern Tee.", "I like to drink tea.", "Mnemonic: gern after a verb means you like doing it.", ["gerne"]),
  word("adv", "zusammen", "together", "tsuˈzamən", "function", "Wir lernen zusammen.", "We study together.", "Mnemonic: zusammen is together; z is /ts/."),

  // prepositions
  word("prep", "in", "in", "ɪn", "function", "Ich wohne in Berlin.", "I live in Berlin.", "Mnemonic: in is in; accusative for motion, dative for place."),
  word("prep", "an", "at / on (vertical)", "an", "function", "Das Bild hängt an der Wand.", "The picture hangs on the wall.", "Mnemonic: an is on a wall or at a river."),
  word("prep", "auf", "on (horizontal)", "aʊf", "function", "Das Buch liegt auf dem Tisch.", "The book is on the table.", "Mnemonic: auf is on a surface you can put something on."),
  word("prep", "unter", "under", "ˈʊntɐ", "function", "Die Tasche ist unter dem Tisch.", "The bag is under the table.", "Mnemonic: unter is under."),
  word("prep", "über", "over / about", "ˈyːbɐ", "function", "Die Lampe hängt über dem Tisch.", "The lamp hangs over the table.", "Mnemonic: über is over; also about a topic."),
  word("prep", "vor", "in front of / before", "foːɐ̯", "function", "Das Taxi wartet vor dem Hotel.", "The taxi waits in front of the hotel.", "Mnemonic: vor is in front or before in time."),
  word("prep", "hinter", "behind", "ˈhɪntɐ", "function", "Der Garten ist hinter dem Haus.", "The garden is behind the house.", "Mnemonic: hinter is behind."),
  word("prep", "neben", "next to", "ˈneːbn̩", "function", "Das Café ist neben dem Kino.", "The cafe is next to the cinema.", "Mnemonic: neben is beside."),
  word("prep", "zwischen", "between", "ˈtsvɪʃn̩", "function", "Ich sitze zwischen euch.", "I sit between you.", "Mnemonic: zwischen is between; z is /ts/."),
  word("prep", "mit", "with", "mɪt", "function", "Ich fahre mit dem Bus.", "I go by bus.", "Mnemonic: mit is with; also the vehicle preposition."),
  word("prep", "ohne", "without", "ˈoːnə", "function", "Ich trinke Kaffee ohne Milch.", "I drink coffee without milk.", "Mnemonic: ohne is without; takes accusative."),
  word("prep", "für", "for", "fyːɐ̯", "function", "Das Geschenk ist für dich.", "The present is for you.", "Mnemonic: für is for; ü, takes accusative."),
  word("prep", "von", "from / of", "fɔn", "function", "Ich komme von der Arbeit.", "I am coming from work.", "Mnemonic: von is from/of; v is /f/."),
  word("prep", "zu", "to", "tsuː", "function", "Ich gehe zu der Schule.", "I am going to the school.", "Mnemonic: zu is to a person or building; z is /ts/."),
  word("prep", "nach", "to (city) / after", "naːx", "function", "Ich fahre nach Berlin.", "I am going to Berlin.", "Mnemonic: nach plus a city; also after in time."),
  word("prep", "aus", "out of / from", "aʊs", "function", "Ich komme aus Spanien.", "I come from Spain.", "Mnemonic: aus plus a country of origin."),
  word("prep", "bei", "at / near", "baɪ", "function", "Ich bin bei Anna.", "I am at Anna's.", "Mnemonic: bei is at someone's place or near."),
  word("prep", "um", "around / at (clock)", "ʊm", "function", "Wir treffen uns um zehn Uhr.", "We meet at ten o'clock.", "Mnemonic: um plus clock time."),
  word("prep", "durch", "through", "dʊʁç", "function", "Wir gehen durch den Park.", "We walk through the park.", "Mnemonic: durch is through; takes accusative."),
  word("prep", "gegen", "against / around (time)", "ˈɡeːɡn̩", "function", "Das Auto fährt gegen die Mauer.", "The car drives against the wall.", "Mnemonic: gegen is against; also around a clock time."),

  // conjunctions
  word("conj", "und", "and", "ʊnt", "function", "Brot und Käse, bitte.", "Bread and cheese, please.", "Mnemonic: und is and; final d as t."),
  word("conj", "oder", "or", "ˈoːdɐ", "function", "Tee oder Kaffee?", "Tea or coffee?", "Mnemonic: oder is or."),
  word("conj", "aber", "but", "ˈaːbɐ", "function", "Klein, aber hell.", "Small but bright.", "Mnemonic: aber is but; does not kick the verb to the end."),
  word("conj", "denn", "because (clause-internal)", "dɛn", "function", "Ich bleibe, denn ich bin müde.", "I am staying, because I am tired.", "Mnemonic: denn is because without changing word order."),
  word("conj", "weil", "because", "vaɪl", "function", "Ich bleibe, weil ich müde bin.", "I am staying because I am tired.", "Mnemonic: weil sends the verb to the end."),
  word("conj", "wenn", "if / when", "vɛn", "function", "Wenn ich Zeit habe, komme ich.", "If I have time, I will come.", "Mnemonic: wenn is if or whenever; als is a one-time past when."),
  word("conj", "dass", "that", "das", "function", "Ich glaube, dass das gut ist.", "I believe that that is good.", "Mnemonic: dass is the conjunction; das is the article/pronoun."),
  word("conj", "sondern", "but rather", "ˈzɔndɐn", "function", "Nicht Tee, sondern Kaffee.", "Not tea, but coffee.", "Mnemonic: sondern follows a nicht and replaces the choice."),
  word("conj", "sowie", "as well as", "zoˈviː", "function", "Brot sowie Käse stehen auf dem Tisch.", "Bread as well as cheese are on the table.", "Mnemonic: so plus wie: as well as."),
  word("conj", "obwohl", "although", "ɔpˈvoːl", "function", "Obwohl es regnet, gehe ich.", "Although it is raining, I am going.", "Mnemonic: obwohl sends the verb to the end."),
  word("conj", "bevor", "before", "bəˈfoːɐ̯", "function", "Bevor ich gehe, trinke ich Tee.", "Before I go, I drink tea.", "Mnemonic: bevor is before as a clause linker."),
  word("conj", "nachdem", "after", "naːxˈdeːm", "function", "Nachdem ich esse, lerne ich.", "After I eat, I study.", "Mnemonic: nach plus dem packed into one linker."),

  // pronouns
  word("pron", "ich", "I", "ɪç", "people", "Ich heiße Lea.", "I am called Lea.", "Mnemonic: ich is I; ich-Laut at the end."),
  word("pron", "du", "you (informal)", "duː", "people", "Wie heißt du?", "What is your name?", "Mnemonic: du is informal you, one person."),
  word("pron", "er", "he", "eːɐ̯", "people", "Er kommt aus Köln.", "He comes from Cologne.", "Mnemonic: er is he."),
  word("pron", "sie", "she / they", "ziː", "people", "Sie wohnen hier.", "They live here.", "Mnemonic: lowercase sie is she or they; capital Sie is formal you."),
  word("pron", "es", "it", "ɛs", "people", "Es ist kalt.", "It is cold.", "Mnemonic: es is it, also the dummy subject."),
  word("pron", "wir", "we", "viːɐ̯", "people", "Wir lernen zusammen.", "We study together.", "Mnemonic: wir is we; w is /v/."),
  word("pron", "ihr", "you (plural informal)", "iːɐ̯", "people", "Wo wohnt ihr?", "Where do you live?", "Mnemonic: ihr is you-all informal, also her as a possessive."),
  word("pron", "Sie", "you (formal)", "ziː", "people", "Wie heißen Sie?", "What is your name?", "Mnemonic: capital Sie is the polite you; tagged formal so the id does not collide with sie.", [], "formal"),
  word("pron", "mich", "me (accusative)", "mɪç", "people", "Kannst du mich hören?", "Can you hear me?", "Mnemonic: mich is me as a direct object."),
  word("pron", "dich", "you (accusative informal)", "dɪç", "people", "Ich sehe dich.", "I see you.", "Mnemonic: dich is informal you as object."),
  word("pron", "uns", "us", "ʊns", "people", "Er sieht uns.", "He sees us.", "Mnemonic: uns is us."),
  word("pron", "euch", "you (plural object)", "ɔʏç", "people", "Ich rufe euch an.", "I will call you.", "Mnemonic: euch is you-all as object."),
  word("pron", "mein", "my", "maɪn", "people", "Das ist mein Buch.", "That is my book.", "Mnemonic: mein is my; endings change with gender."),
  word("pron", "dein", "your (informal)", "daɪn", "people", "Ist das dein Schlüssel?", "Is that your key?", "Mnemonic: dein is informal your."),
  word("pron", "unser", "our", "ˈʊnzɐ", "people", "Das ist unser Haus.", "That is our house.", "Mnemonic: unser is our."),
  word("pron", "dieser", "this / that", "ˈdiːzɐ", "people", "Dieser Zug fährt nach Berlin.", "This train goes to Berlin.", "Mnemonic: dieser points at a specific noun."),
  word("pron", "jeder", "each / every", "ˈjeːdɐ", "people", "Jeder Tag ist anders.", "Each day is different.", "Mnemonic: jeder is every one."),
  word("pron", "alle", "all / everyone", "ˈalə", "people", "Alle sind hier.", "Everyone is here.", "Mnemonic: alle is all the people."),
  word("pron", "etwas", "something", "ˈɛtvas", "function", "Ich brauche etwas Wasser.", "I need some water.", "Mnemonic: etwas is something or some."),
  word("pron", "nichts", "nothing", "nɪçts", "function", "Ich verstehe nichts.", "I understand nothing.", "Mnemonic: nichts is nothing; ich-Laut plus ts."),
  word("pron", "man", "one / people", "man", "people", "Man spricht hier Deutsch.", "People speak German here.", "Mnemonic: man is the generic one, not der Mann.", [], "generic"),
  word("pron", "wer", "who", "veːɐ̯", "people", "Wer ist das?", "Who is that?", "Mnemonic: wer is who; w is /v/."),

  // numbers
  word("num", "null", "zero", "nʊl", "numbers", "Es ist null Uhr.", "It is zero o'clock.", "Mnemonic: null is zero."),
  word("num", "eins", "one", "aɪns", "numbers", "Ich habe eins.", "I have one.", "Mnemonic: eins stands alone; ein is the article form."),
  word("num", "zwei", "two", "tsvaɪ", "numbers", "Zwei Kaffee, bitte.", "Two coffees, please.", "Mnemonic: zwei starts with /ts/."),
  word("num", "drei", "three", "dʁaɪ", "numbers", "Wir sind drei.", "There are three of us.", "Mnemonic: drei is three."),
  word("num", "vier", "four", "fiːɐ̯", "numbers", "Das kostet vier Euro.", "That costs four euros.", "Mnemonic: vier is four; v is /f/."),
  word("num", "fünf", "five", "fʏnf", "numbers", "Fünf Minuten, bitte.", "Five minutes, please.", "Mnemonic: fünf has ü; short and rounded."),
  word("num", "sechs", "six", "zɛks", "numbers", "Um sechs Uhr.", "At six o'clock.", "Mnemonic: sechs is six; chs as /ks/."),
  word("num", "sieben", "seven", "ˈziːbn̩", "numbers", "Wir kommen um sieben.", "We are coming at seven.", "Mnemonic: sieben is seven."),
  word("num", "acht", "eight", "axt", "numbers", "Es ist acht Uhr.", "It is eight o'clock.", "Mnemonic: acht is eight; ach-Laut."),
  word("num", "neun", "nine", "nɔʏn", "numbers", "Ich arbeite bis neun.", "I work until nine.", "Mnemonic: neun is nine; eu as in Deutsch."),
  word("num", "zehn", "ten", "tseːn", "numbers", "Der Zug fährt um zehn.", "The train leaves at ten.", "Mnemonic: zehn starts with /ts/; long e."),
  word("num", "elf", "eleven", "ɛlf", "numbers", "Es ist elf Uhr.", "It is eleven o'clock.", "Mnemonic: elf is eleven."),
  word("num", "zwölf", "twelve", "tsvœlf", "numbers", "Um zwölf ist Mittag.", "At twelve it is midday.", "Mnemonic: zwölf has ö; z is /ts/."),
  word("num", "zwanzig", "twenty", "ˈtsvantsɪç", "numbers", "Ich bin zwanzig.", "I am twenty.", "Mnemonic: zwanzig; -ig is /ɪç/."),
  word("num", "hundert", "hundred", "ˈhʊndɐt", "numbers", "Das kostet hundert Euro.", "That costs a hundred euros.", "Mnemonic: hundert is hundred."),
  word("num", "tausend", "thousand", "ˈtaʊzn̩t", "numbers", "Tausend Dank!", "A thousand thanks!", "Mnemonic: tausend is thousand."),

  // other
  word("other", "ja", "yes", "jaː", "function", "Ja, bitte.", "Yes, please.", "Mnemonic: ja is yes; j as English y."),
  word("other", "nein", "no", "naɪn", "function", "Nein, danke.", "No, thank you.", "Mnemonic: nein is no; ei as in mine."),
  word("other", "bitte", "please / you're welcome", "ˈbɪtə", "function", "Einen Kaffee, bitte.", "A coffee, please.", "Mnemonic: bitte covers please, go ahead, and you're welcome."),
  word("other", "danke", "thank you", "ˈdaŋkə", "function", "Danke für die Hilfe.", "Thank you for the help.", "Mnemonic: danke is thanks."),
  word("other", "hallo", "hello", "haˈloː", "people", "Hallo, wie geht’s?", "Hello, how are you?", "Mnemonic: hallo is the informal hello."),
  word("other", "tschüss", "bye", "tʃyːs", "people", "Tschüss, bis morgen!", "Bye, see you tomorrow!", "Mnemonic: tschüss is informal goodbye."),
  word("other", "Hilfe", "help", "ˈhɪlfə", "function", "Hilfe, bitte!", "Help, please!", "Mnemonic: Hilfe is the shout and the noun help."),
  word("other", "Willkommen", "welcome", "vɪlˈkɔmən", "people", "Willkommen in Berlin!", "Welcome to Berlin!", "Mnemonic: Willkommen is welcome."),
  word("other", "Entschuldigung", "excuse me / sorry", "ɛntˈʃʊldɪɡʊŋ", "function", "Entschuldigung, wo ist der Bahnhof?", "Excuse me, where is the station?", "Mnemonic: long courtesy word for getting attention or a small sorry."),
  word("other", "okay", "okay", "oˈkeː", "function", "Okay, ich komme.", "Okay, I am coming.", "Mnemonic: okay is a loan; stress the second syllable.", ["ok"]),
  word("other", "Deutsch", "German (language)", "dɔʏtʃ", "school", "Ich lerne Deutsch.", "I am learning German.", "Mnemonic: Deutsch is the language name; eu as ɔʏ."),
  word("other", "Prost", "cheers", "pʁoːst", "food", "Prost!", "Cheers!", "Mnemonic: Prost is the informal toast."),
  word("other", "Super", "great", "ˈzuːpɐ", "function", "Super, das klappt!", "Great, that works!", "Mnemonic: Super is a loan used as a reaction."),
];

export const CORE_LEXICON: CoreLexeme[] = [...NOUNS, ...VERBS, ...ADJECTIVES, ...FUNCTION_WORDS];

