import type { Phrase } from "@syncspace/contracts";

const draft = "draft" as const;

function phrase(
  id: string,
  de: string,
  en: string,
  ipa: string,
  topic: string,
  situationEn: string,
  notesEn: string,
): Phrase {
  return { id, de, en, ipa, topic, situationEn, notesEn, contentStatus: draft };
}

export const PHRASES: Phrase[] = [
  phrase("phr-hallo", "Hallo!", "Hello!", "haˈloː", "greetings", "Informal hello.", "Fine with classmates. Guten Tag is safer with strangers."),
  phrase("phr-guten-tag", "Guten Tag!", "Good day / hello.", "ˈɡuːtn̩ taːk", "greetings", "Neutral daytime greeting.", "Standard in shops and offices."),
  phrase("phr-guten-morgen", "Guten Morgen!", "Good morning.", "ˈɡuːtn̩ ˈmɔʁɡn̩", "greetings", "Until late morning.", "Morgen alone is a shorter informal form."),
  phrase("phr-guten-abend", "Guten Abend!", "Good evening.", "ˈɡuːtn̩ ˈaːbn̩t", "greetings", "After work, into the evening.", "Not used at noon."),
  phrase("phr-gute-nacht", "Gute Nacht!", "Good night.", "ˈɡuːtə naxt", "greetings", "When someone is going to bed.", "A farewell, not a hello."),
  phrase("phr-tschuss", "Tschüss!", "Bye!", "tʃyːs", "greetings", "Informal goodbye.", "Auf Wiedersehen is the formal pair."),
  phrase("phr-wiedersehen", "Auf Wiedersehen!", "Goodbye.", "aʊf ˈviːdɐzeːən", "greetings", "Formal goodbye.", "Literally until seeing-again."),
  phrase("phr-bitte", "Bitte.", "Please / you're welcome / go ahead.", "ˈbɪtə", "courtesy", "Offering, requesting, or answering danke.", "Context decides the English."),
  phrase("phr-danke", "Danke!", "Thank you!", "ˈdaŋkə", "courtesy", "Any small thanks.", "Vielen Dank is stronger."),
  phrase("phr-vielen-dank", "Vielen Dank!", "Many thanks.", "ˈfiːlən daŋk", "courtesy", "When someone really helped.", "Still everyday, not ceremonial."),
  phrase("phr-bitte-schoen", "Bitte schön.", "You're welcome.", "ˈbɪtə ʃøːn", "courtesy", "Reply to danke.", "Gern geschehen is another reply."),
  phrase("phr-entschuldigung", "Entschuldigung!", "Excuse me / sorry.", "ɛntˈʃʊldɪɡʊŋ", "courtesy", "Getting past someone or a small apology.", "More formal than sorry in English tone."),
  phrase("phr-es-tut-mir-leid", "Es tut mir leid.", "I am sorry.", "ɛs tuːt miːɐ̯ laɪt", "courtesy", "A real apology.", "Not for squeezing past in a shop."),
  phrase("phr-kein-problem", "Kein Problem.", "No problem.", "kaɪn pʁoˈbleːm", "courtesy", "Reassuring someone.", "Also a DW lesson title; our line is a stock phrase."),
  phrase("phr-ja", "Ja.", "Yes.", "jaː", "basics", "Agreement.", "Doch answers a negative question (Hast du keine Zeit? — Doch!)."),
  phrase("phr-nein", "Nein.", "No.", "naɪn", "basics", "Refusal or correction.", "Pair with danke when refusing an offer: Nein, danke."),
  phrase("phr-nein-danke", "Nein, danke.", "No, thank you.", "naɪn ˈdaŋkə", "basics", "Polite refusal.", "Ja, bitte accepts an offer."),
  phrase("phr-ja-bitte", "Ja, bitte.", "Yes, please.", "jaː ˈbɪtə", "basics", "Accepting an offer.", "Common when a waiter asks."),
  phrase("phr-wie-heisst-du", "Wie heißt du?", "What is your name?", "viː haɪst duː", "intro", "Informal introductions.", "Formal: Wie heißen Sie?"),
  phrase("phr-ich-heisse", "Ich heiße …", "My name is …", "ɪç ˈhaɪsə", "intro", "Giving your name.", "heißen is to be called, not to be named as a title."),
  phrase("phr-ich-komme-aus", "Ich komme aus …", "I come from …", "ɪç ˈkɔmə aʊs", "intro", "Country or town of origin.", "Use aus + country: aus Spanien."),
  phrase("phr-ich-wohne-in", "Ich wohne in …", "I live in …", "ɪç ˈvoːnə ɪn", "intro", "Current city.", "wohnen is live-somewhere; leben is broader live."),
  phrase("phr-freut-mich", "Freut mich.", "Nice to meet you.", "fʁɔʏt mɪç", "intro", "After names.", "Longer: Freut mich, Sie kennenzulernen."),
  phrase("phr-sprechen-sie", "Sprechen Sie Deutsch?", "Do you speak German?", "ˈʃpʁɛçn̩ ziː dɔʏtʃ", "intro", "Formal question.", "Informal: Sprichst du Deutsch?"),
  phrase("phr-ich-verstehe-nicht", "Ich verstehe das nicht.", "I do not understand that.", "ɪç fɛɐ̯ˈʃteːə das nɪçt", "study", "In class or at a counter.", "Langsamer, bitte can follow."),
  phrase("phr-langsamer", "Langsamer, bitte.", "More slowly, please.", "ˈlaŋzaːmɐ ˈbɪtə", "study", "When speech is too fast.", "Wiederholen Sie das, bitte asks for a repeat."),
  phrase("phr-wiederholen", "Wiederholen Sie das, bitte.", "Please repeat that.", "ˈviːdɐhoːlən ziː das ˈbɪtə", "study", "Formal request to hear it again.", "Informal: Wiederhol das bitte."),
  phrase("phr-wie-bitte", "Wie bitte?", "Pardon?", "viː ˈbɪtə", "study", "You missed a word.", "Politer than Was?"),
  phrase("phr-was-bedeutet", "Was bedeutet …?", "What does … mean?", "vas bəˈdɔʏtət", "study", "Asking for a gloss.", "Fill the gap with the German word."),
  phrase("phr-ich-lerne", "Ich lerne Deutsch.", "I am learning German.", "ɪç ˈlɛʁnə dɔʏtʃ", "study", "Explaining why your German is simple.", "studieren is for a university subject."),
  phrase("phr-wo-ist", "Wo ist …?", "Where is …?", "voː ɪst", "city", "Finding a place.", "Add the article: Wo ist der Bahnhof?"),
  phrase("phr-wie-komme-ich", "Wie komme ich zum Bahnhof?", "How do I get to the station?", "viː ˈkɔmə ɪç tsʊm ˈbaːnhoːf", "city", "Asking the way.", "zum = zu dem."),
  phrase("phr-links", "Links, dann rechts.", "Left, then right.", "lɪŋks dan ʁɛçts", "city", "Short directions.", "geradeaus is straight on."),
  phrase("phr-geradeaus", "Immer geradeaus.", "Straight on all the way.", "ˈɪmɐ ɡəˈʁaːdəʔaʊs", "city", "When there is no turn.", "immer here means keep going."),
  phrase("phr-eine-fahrkarte", "Eine Fahrkarte nach Berlin, bitte.", "A ticket to Berlin, please.", "ˈaɪnə ˈfaːɐ̯kaʁtə naːx bɛʁˈliːn ˈbɪtə", "travel", "At a counter.", "nach + city."),
  phrase("phr-wann-faehrt", "Wann fährt der Zug?", "When does the train leave?", "van fɛːɐ̯t deːɐ̯ tsuːk", "travel", "Platform or desk.", "fahren takes a vowel change: er fährt."),
  phrase("phr-ich-moechte", "Ich möchte einen Kaffee.", "I would like a coffee.", "ɪç ˈmœçtə ˈaɪnən ˈkafe", "food", "Ordering.", "möchte is the polite want. einen is accusative masculine."),
  phrase("phr-die-rechnung", "Die Rechnung, bitte.", "The bill, please.", "diː ˈʁɛçnʊŋ ˈbɪtə", "food", "Leaving a café.", "Also Zahlen, bitte."),
  phrase("phr-prost", "Prost!", "Cheers!", "pʁoːst", "food", "Raising a glass.", "Informal. Zum Wohl is another toast."),
  phrase("phr-guten-appetit", "Guten Appetit!", "Enjoy your meal.", "ˈɡuːtn̩ apəˈtiːt", "food", "When food arrives.", "Reply: Danke, ebenfalls."),
  phrase("phr-wie-viel-kostet", "Wie viel kostet das?", "How much does that cost?", "viː fiːl ˈkɔstət das", "shop", "Price check.", "Was kostet …? is the same idea."),
  phrase("phr-ich-nehme", "Ich nehme das.", "I’ll take that.", "ɪç ˈneːmə das", "shop", "Choosing an item.", "Accusative das."),
  phrase("phr-haben-sie", "Haben Sie …?", "Do you have …?", "ˈhaːbn̩ ziː", "shop", "Formal stock question.", "Fill with an accusative noun."),
  phrase("phr-oeffnungszeiten", "Wann haben Sie auf?", "When are you open?", "van ˈhaːbn̩ ziː aʊf", "shop", "Hours.", "aufhaben = be open."),
  phrase("phr-hilfe", "Hilfe!", "Help!", "ˈhɪlfə", "help", "Emergency shout.", "Use Entschuldigung for ordinary attention."),
  phrase("phr-wo-ist-toilette", "Wo ist die Toilette?", "Where is the toilet?", "voː ɪst diː toaˈlɛtə", "help", "In a café or station.", "das WC is also common."),
  phrase("phr-ich-bin-krank", "Ich bin krank.", "I am ill.", "ɪç bɪn kraŋk", "help", "At a doctor or cancelling.", "Mir ist schlecht is I feel sick."),
  phrase("phr-rufen-sie", "Rufen Sie einen Arzt!", "Call a doctor!", "ˈʁuːfn̩ ziː ˈaɪnən aːɐ̯tst", "help", "Urgent formal request.", "einen Arzt is accusative."),
  phrase("phr-wie-spaet", "Wie spät ist es?", "What time is it?", "viː ʃpɛːt ɪst ɛs", "time", "Asking the clock.", "Answer: Es ist acht Uhr."),
  phrase("phr-es-ist-uhr", "Es ist acht Uhr.", "It is eight o’clock.", "ɛs ɪst axt uːɐ̯", "time", "Full hours.", "halb acht is 7:30."),
  phrase("phr-bis-morgen", "Bis morgen!", "See you tomorrow.", "bɪs ˈmɔʁɡn̩", "time", "Informal farewell.", "Bis später / Bis bald are looser."),
  phrase("phr-ich-habe-termin", "Ich habe um zehn Uhr einen Termin.", "I have an appointment at ten.", "ɪç ˈhaːbə ʊm tseːn uːɐ̯ ˈaɪnən tɛɐ̯ˈmiːn", "time", "Explaining a schedule.", "um + clock time."),
  phrase("phr-alles-klar", "Alles klar?", "All clear / got it?", "ˈaləs klaːɐ̯", "chat", "Checking understanding.", "Informal. Also used as a reply: Alles klar."),
  phrase("phr-super", "Super!", "Great!", "ˈzuːpɐ", "chat", "Positive reaction.", "Loanword, everyday."),
  phrase("phr-kein-plan", "Ich habe keine Ahnung.", "I have no idea.", "ɪç ˈhaːbə ˈkaɪnə ˈaːnʊŋ", "chat", "You cannot help with a fact.", "Ahnung is a hunch / clue."),
  phrase("phr-wie-gehts", "Wie geht’s?", "How are you?", "viː ɡeːts", "chat", "Informal check-in.", "Full: Wie geht es dir? Formal: Wie geht es Ihnen?"),
  phrase("phr-gut-danke", "Gut, danke. Und dir?", "Fine, thanks. And you?", "ɡuːt ˈdaŋkə ʊnt diːɐ̯", "chat", "Reply to Wie geht’s?", "Formal reply uses Ihnen."),
  phrase("phr-ich-bin-muede", "Ich bin müde.", "I am tired.", "ɪç bɪn ˈmyːdə", "chat", "Simple state.", "müde is an adjective after sein."),
  phrase("phr-schoen-dich", "Schön, dich zu sehen.", "Good to see you.", "ʃøːn dɪç tsuː ˈzeːən", "chat", "Meeting someone you know.", "Formal: Schön, Sie zu sehen."),
  phrase("phr-willkommen", "Willkommen!", "Welcome!", "vɪlˈkɔmən", "greetings", "Greeting a guest.", "Willkommen in Berlin names the place."),
  phrase("phr-wetter", "Wie ist das Wetter?", "What’s the weather like?", "viː ɪst das ˈvɛtɐ", "weather", "Small talk or planning a walk.", "Answer with Es ist … or Es regnet."),
  phrase("phr-es-regnet", "Es regnet.", "It is raining.", "ɛs ˈʁeːɡnət", "weather", "Looking out of the window.", "regnen is impersonal: es regnet."),
  phrase("phr-es-schneit", "Es schneit.", "It is snowing.", "ɛs ʃnaɪt", "weather", "Winter small talk.", "Same es-pattern as Es regnet."),
  phrase("phr-sonne", "Die Sonne scheint.", "The sun is shining.", "diː ˈzɔnə ʃaɪnt", "weather", "A clear day.", "scheinen: er/sie/es scheint."),
  phrase("phr-es-ist-kalt", "Es ist kalt.", "It is cold.", "ɛs ɪst kalt", "weather", "Temperature.", "Swap kalt for warm, heiß, oder kühl."),
  phrase("phr-zu-hause", "Ich bin zu Hause.", "I am at home.", "ɪç bɪn tsuː ˈhaʊzə", "home", "Saying where you are.", "zu Hause is the set phrase; nach Hause is direction."),
  phrase("phr-komm-rein", "Komm rein!", "Come in!", "kɔm ʁaɪn", "home", "Opening the door to a friend.", "Informal. Formal: Kommen Sie herein!"),
  phrase("phr-wo-kueche", "Wo ist die Küche?", "Where is the kitchen?", "voː ɪst diː ˈkʏçə", "home", "In a shared flat or a host’s home.", "Same Wo ist + article frame as the city lines."),
  phrase("phr-ich-raeume", "Ich räume auf.", "I am tidying up.", "ɪç ˈʁɔʏmə aʊf", "home", "Explaining the mess.", "Separable: aufräumen → ich räume … auf."),
  phrase("phr-hier-ist", "Hallo, hier ist Anna.", "Hello, this is Anna.", "ˈhalo hiːɐ̯ ɪst ˈana", "phone", "Starting a call.", "Replace Anna with your name. hier ist names the speaker."),
  phrase("phr-hoeren", "Kannst du mich hören?", "Can you hear me?", "kanst duː mɪç ˈhøːʁən", "phone", "A bad line.", "Formal: Können Sie mich hören?"),
  phrase("phr-rufe-an", "Ich rufe später an.", "I will call later.", "ɪç ˈʁuːfə ˈʃpɛːtɐ an", "phone", "Ending a call.", "Separable: anrufen → ich rufe … an."),
  phrase("phr-eine-frage", "Ich habe eine Frage.", "I have a question.", "ɪç ˈhaːbə ˈaɪnə ˈfʁaːɡə", "study", "Before interrupting a class.", "eine Frage is accusative feminine."),
  phrase("phr-welche-seite", "Welche Seite?", "Which page?", "ˈvɛlçə ˈzaɪtə", "study", "Finding the place in a book.", "Seite is feminine: die Seite."),
  phrase("phr-nicht-verstanden", "Das habe ich nicht verstanden.", "I did not understand that.", "das ˈhaːbə ɪç nɪçt fɛɐ̯ˈʃtandn̩", "study", "After a fast explanation.", "Understood uses the participle verstanden."),
  phrase("phr-kopf-weh", "Mein Kopf tut weh.", "My head hurts.", "maɪn kɔpf tuːt veː", "help", "At a pharmacy or with a friend.", "weh tun: es tut weh. Possessive matches the body part."),
  phrase("phr-brauche-wasser", "Ich brauche Wasser.", "I need water.", "ɪç ˈbʁaʊxə ˈvasɐ", "help", "Thirst or after sport.", "brauchen takes an accusative object. Wasser has no article here."),
  phrase("phr-heute-zeit", "Heute habe ich Zeit.", "I have time today.", "ˈhɔʏtə ˈhaːbə ɪç tsaɪt", "time", "Accepting a plan.", "Zeit without an article means time-available."),
  phrase("phr-morgen-arbeiten", "Morgen muss ich arbeiten.", "I have to work tomorrow.", "ˈmɔʁɡn̩ mʊs ɪç ˈaʁbaɪtn̩", "time", "Turning a plan down.", "Modal muss, infinitive at the end."),
];
