import type { SkillResource } from "@syncspace/contracts";

/** Official and public pages only. We do not host their audio, PDFs, or exam items. */
export const SKILL_RESOURCES: SkillResource[] = [
  {
    id: "sk-listen-goethe-a1",
    skill: "listen",
    title: "Goethe-Institut: A1 Prüfungstraining (Hören)",
    url: "https://www.goethe.de/de/spr/prf/ueb/pa1.html",
    levelTag: "A1",
    useEn: "Official listening, reading, writing, and speaking practice for Start Deutsch 1. Stay on the Goethe site; we do not copy the papers.",
    localPath: "/learn/sounds",
  },
  {
    id: "sk-listen-dw-news",
    skill: "listen",
    title: "Deutsche Welle: Deutsch lernen mit Nachrichten",
    url: "https://learngerman.dw.com/de/deutsch-lernen-mit-nachrichten/s-66405122",
    levelTag: "A2–B2",
    useEn: "Hub for DW news video (A2), Top-Thema (B1), and slowly spoken news (B2). Audio stays on DW.",
  },
  {
    id: "sk-listen-dw-slow",
    skill: "listen",
    title: "Deutsche Welle: Langsam gesprochene Nachrichten",
    url: "https://learngerman.dw.com/de/langsam-gesprochene-nachrichten/s-60040332",
    levelTag: "B2",
    useEn: "Daily news read slowly, with a transcript. Labeled B2 by DW; useful later, not a first-week drill.",
  },
  {
    id: "sk-listen-nicos",
    skill: "listen",
    title: "Deutsche Welle: Nicos Weg videos",
    url: "https://learngerman.dw.com/en/nicos-weg/c-36519789",
    levelTag: "A1–B1",
    useEn: "Short video lessons from the first greeting onward. Watch on DW; pair with our phrase list afterwards.",
    localPath: "/learn/phrases",
  },
  {
    id: "sk-read-goethe-a1",
    skill: "read",
    title: "Goethe-Institut: A1 Prüfungstraining (Lesen)",
    url: "https://www.goethe.de/de/spr/prf/ueb/pa1.html",
    levelTag: "A1",
    useEn: "Short notices and everyday texts in the official A1 set. Open the Lesen tasks on Goethe.",
    localPath: "/learn/words",
  },
  {
    id: "sk-read-dw-news",
    skill: "read",
    title: "Deutsche Welle: news texts with audio",
    url: "https://learngerman.dw.com/de/deutsch-lernen-mit-nachrichten/s-66405122",
    levelTag: "A2–B1",
    useEn: "Read the transcript first, then listen. DW hosts the articles.",
  },
  {
    id: "sk-read-nachrichtenleicht",
    skill: "read",
    title: "Deutschlandfunk: Nachrichtenleicht",
    url: "https://www.nachrichtenleicht.de/",
    levelTag: "A2+",
    useEn: "Public easy-language news from Deutschlandfunk. Current articles, not a word list we store.",
  },
  {
    id: "sk-write-goethe-a1",
    skill: "write",
    title: "Goethe-Institut: A1 Prüfungstraining (Schreiben)",
    url: "https://www.goethe.de/de/spr/prf/ueb/pa1.html",
    levelTag: "A1",
    useEn: "Form-filling and a short message in the official A1 set. Write on paper or in the Goethe trainer.",
    localPath: "/learn/builder",
  },
  {
    id: "sk-write-builder",
    skill: "write",
    title: "Sentence builder on this device",
    url: "https://www.goethe.de/de/spr/prf/ueb.html",
    levelTag: "A1",
    useEn: "Assemble a finite A1 clause from the core list, then compare with a Goethe writing task. The builder never invents extra German.",
    localPath: "/learn/builder",
  },
  {
    id: "sk-speak-goethe-a1",
    skill: "speak",
    title: "Goethe-Institut: A1 Prüfungstraining (Sprechen)",
    url: "https://www.goethe.de/de/spr/prf/ueb/pa1.html",
    levelTag: "A1",
    useEn: "Official speaking sample and partner tasks. We do not score speech. A device voice is not a teacher.",
    localPath: "/learn/phrases",
  },
  {
    id: "sk-speak-sounds",
    skill: "speak",
    title: "Alphabet and sounds on this device",
    url: "https://en.wikipedia.org/wiki/Help:IPA/Standard_German",
    levelTag: "A1",
    useEn: "Draft IPA plus optional browser voice. Then open Goethe Sprechen for a human model.",
    localPath: "/learn/sounds",
  },
  {
    id: "sk-speak-nicos",
    skill: "speak",
    title: "Deutsche Welle: Nicos Weg dialogues",
    url: "https://learngerman.dw.com/en/nicos-weg/c-36519789",
    levelTag: "A1",
    useEn: "Pause a DW dialogue and repeat the line. Pair with our greetings list.",
    localPath: "/learn/phrases",
  },
];

export const SKILL_GUIDES = {
  listen: {
    titleEn: "Listening",
    summaryEn: "Hear slow, official audio on Goethe and Deutsche Welle. On this device you can only preview letter names and draft IPA with the browser voice.",
    localEn: "Warm up on Sounds, then open a Goethe Hören set or a DW clip.",
  },
  read: {
    titleEn: "Reading",
    summaryEn: "Read short public texts. The core-500 is a word bank, not a reader.",
    localEn: "Look up an unknown noun in Inquiry, then return to the article.",
  },
  write: {
    titleEn: "Writing",
    summaryEn: "Produce a finite clause here, then try an official form or short message on Goethe.",
    localEn: "Use the sentence builder so the article and accusative stay consistent.",
  },
  speak: {
    titleEn: "Speaking",
    summaryEn: "Repeat official models. Device speech synthesis is a reminder, not pronunciation teaching.",
    localEn: "Say a phrase from the list, then watch a Goethe Sprechen sample.",
  },
} as const;
